### ISSUE TITLE
Add documentation about the database

### ISSUE THREAD

**Issue by CVTJNII** [SUSE/Portus#1105]
In poking around compose I see a MariaDB database is required, which is apparently bootstrapped by a rake task.  However, I cannot locate the official documentation about the database, such as what DBs are supported (MariaDB and supposedly MySQL are supported, how about Postgres?) or how to manage it.

Please expand the documentation to include:
- Which Database backends are supported
- How Portus is configured to connect to the DB
- How the DB is bootstrapped
- If a central DB cluster is required for production (I'm assuming yes?)

**Comment by mssola** [comment]
Thanks for bringing up this topic, since it has been worked on lately (see PR #1093). The official statement would be that Portus supports MariaDB, but as you can see in the PR #1093, this can be made more flexible in the future.

After I get more feedback in PR #1093, I'll write the documentation that you are mentioning. That being said, the RPM will most surely still require MariaDB, so this flexibility will only be available for container setups and bare metal solutions.

**Comment by CVTJNII** [comment]
Sounds good!  More flexibility would be nice as we would prefer to run Postgres if possible as we have more in-house expertise on it.
