### ISSUE TITLE
Access Denied while setting up

### ISSUE THREAD

**Issue by millerbill3** [SUSE/Portus#1116]
I'm trying to set up Portus on a local VM per the instructions on the website. I've run the command `portusctl setup --ssl-gen-self-signed-certs` and the certificates are created and the installation begins. Eventually I see the following: 
```
Creating Portus' database
Access denied for user 'portus'@'localhost' (using password: YES)Please provide the root password for your MySQL installation
```
I have tried numerous passwords, including the system root password without success so the installation fails and is aborted.
Am I missing something here?

**Comment by mssola** [comment]
This usually is about a misconfigured mysql or that you have to use the proper user/password. For the configuration part, one usual pitfall is not having run at least `mysql_secure_installation`. Otherwise, make sure that the user/password can in fact login with a mysql client. Moreover, note that you can also pass the user/password to be used for mysql with the `--db-name` and `--db-password` flags.

**Comment by millerbill3** [comment]
Was my fault... I failed to run `/usr/bin/mysql_secure_installation` before running the setup.
