### ISSUE TITLE
Limits/quotas

### ISSUE THREAD

**Issue by Djelibeybi** [SUSE/Portus#1127]
Is there any way in Portus to limit the amount of personal repos a user can create in their namespace or the amount of space consumed by user/group?

If not, I'd like to suggest this as an enhancement request. I suspect space consumption quotas would be very challenging, but it would be great to have a limit on at least the number of personal repos. Or be able to disable them completely.

**Comment by holgerreif** [comment]
Right now thre is only the possibility to disable the creation of additional namespaces (see [Granular user permissions](http://port.us.org/docs/Configuring-Portus.html#granular-user-permissions) @ doc.

Controlling of space consumption caused by a dedicated user is as tricky as reporting space consumption, given the sharing of image layers. Lots of repos each having multiple tags could just consume small amount of additional space because all of them are based on the same base image (that is in another repo).

Do you have an idea about what would be the right notion of "consumed space"? How would you calculate this space consumtion?

**Comment by Djelibeybi** [comment]
Calculating space consumption is almost impossible for exactly the reasons you mention, but I can dream, right? :)

For now, it's probably enough just to:

1. Allow the admin to disable the creation of the personal namespaces completely
2. Allow the admin to limit the number of repos that can be created in a personal namespace

**Comment by holgerreif** [comment]
Dreaming opens new horizons ;-)

Another problem with this comes to my mind. AFAIK pushing means: first a user uploads the image blobs and then uploads a manifest referencing the image blobs. Upload of the manifest could be prohibited cause the user has now rights to do so, but the blobs remain until the next garbage collection.

But yes, completely disable the creation of personal namespaces sounds like a good idea for me too.
Limiting the number of repos, I'm sure....

**Comment by Djelibeybi** [comment]
In terms of limiting repos in a namespace, I'm not sure what the push process for a new repo into a namespace is, i.e. whether Portus could stop a push before the image blobs are sent if there are already X (where X is the limit) repos in the namespace.

**Comment by mssola** [comment]
This is something that can be certainly implemented into Portus, but I'm not sure whether it would be too useful. As in, as a sysadmin I'd worry more about the disk space being consumed than the amount of repos (e.g. 100 small repos vs 1 *huge* repo).

This is specially tricky because you can theoretically fetch the size of the different layers from the [manifest](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#image-manifest-field-descriptions), but when pushing a new image, some of these layers may already be available and so you cannot just measure it by summing the total of bytes. This means that we could either cache it somehow, or it can become quite an expensive operation. Moreover, when computing the total size of the layers you don't really know who pushed each layer, so this kind of restriction becomes impossible (plus there's the possibility that the same layer is shared by multiple people).

All in all, we could limit the amount of repositories created by users/teams, but I'm not sure whether this would be useful or not in the end.

**Comment by holgerreif** [comment]
I thought a little bit about the quota problem and came to the following modell: I call it relative space usage. Each image layer size is divided by the number of tags that reference this layer directly or indirectly. 

To give an example: there is a 90MB base image. two images are derived from it, One image (A) has another 10 MB layer and is tagged with one tag, the other image (B) is tagged with 2 tags and has a layer of 20MB on top of the base image. The relative space consumtion of (A) is 90*(1/3)+10=40. Each tag of B has a relative space consumption of 90*(1/3)+20*(1/2)=40. So Repo with image A has 40MB relative space usage, repo of image B has 2*40MB relative space usage. And you guess: 40+80 is exactly the size of all image layers (90+10+20).

This is a fair metric since it rewards sharing of image layers. Furthermore it rewards the usage of your image layers by other users. A slight drawback of the modell is that the relative space usage can increase if other images sharing the same image are deleted.

On the alorithmic side you need to store for every image it's anestor and the number of tags using this image. for every push and delete the numbers of tags for all referenced needed to be adjusted. To get the relative usage one needs to traverse all ancestor layers and sum up the layer size divided by the number of referencing tags.

**Comment by mssola** [comment]
This can be implemented after 2.5 since it depends on some features scheduled with those releases.
