### ISSUE TITLE
Admin approval for new users

### ISSUE THREAD

**Issue by Djelibeybi** [SUSE/Portus#1128]
Currently, the only restriction on the creation of local users is either to enable or disable the signup form. 

This is an enhancement request to add an option that requires admin approval to enable a user account after someone signs up via the signup form.

Possible Workflow:

1. User signs up via web form
2. Account is created in "Disabled" mode
3. Admin is emailed a notification that a user has signed up
4. Admin reviews the user registration and switches to Enabled (if approved)

**Comment by mssola** [comment]
I think that the current workflow wanted to avoid this specific path :smile: In my opinion the way to go if you want to implement such scenario is to disable the signup form and expect users to email an admin so it can be added into Portus. I admit that currently the UI could be better at pointing this (we could have a help section on the login form when signup is disabled that tells users to contact administrator X if they want to use Portus).

**Comment by mssola** [comment]
Re-puposing this issue as an enhancement:

- When signup is disabled, we should have a way to tell users to contact an administrator.
- We could also add a way to set a user as an administrator that could be contacted or something like that.

This won't be implemented in neither 2.4 nor 2.5, since both these releases have already been planned and it has a low priority.
