### ISSUE TITLE
How does authorization work

### ISSUE THREAD

**Issue by hybmg57** [SUSE/Portus#1145]
How does authorization work when I do "docker login dockerhub.domain.com" do I need to reolve this domain to Docker Distribution or Portus? If it gets resolved to Docker Distribution how do you authorize user based on ACL in Portus as it gets resolved to Docker Distribution first instead of Portus?

I would have thought it gets resolved to Portus but the documentation is not really clear on this part.

Also how would this work with Portus that has LDAP integrated?

Thanks

**Comment by mssola** [comment]
Hi @hybmg57. Developer-related material is located on the wiki. Specifically, what you are asking is [here](https://github.com/SUSE/Portus/wiki/Authentication).

The TL;DR version would be that Portus will receive an authorization request from the registry, with all the data, and then it will act upon the request accordingly. The same happens on push/pull requests.

> Also how would this work with Portus that has LDAP integrated?

In the case of LDAP, when Portus receives the authorization request that I mentioned before, instead of hitting the database it performs an LDAP request to the configured LDAP server.

Does this help ?
