### ISSUE TITLE
Cross data center replication

### ISSUE THREAD

**Issue by aaron0428** [SUSE/Portus#1246]
Does Portus have a images replication function like a harbor?

**Comment by mssola** [comment]
What do you exactly mean by this ? Could you describe the feature ?

**Comment by aaron0428** [comment]
Harbor: 跨数据中心复制Docker镜像

**Comment by mssola** [comment]
I see. In this case no. And I honestly don't know whether this should be implemented on Portus or in docker distribution, since this looks like a feature a bit out of the scope from a registry authorization service (I see that harbor also extends the registry, so it's more than an authorization service).
