### ISSUE TITLE
Token are generated for unauthenticated users

### ISSUE THREAD

**Issue by jgoret** [SUSE/Portus#1277]
Hello,

We're currently using Portus to secure our private registry and allow our clients to store images before running them in production. During some security testing, we found that we could get a token without being authenticated and then re-forged to allow push/pull access to any existing repository (which can be listed with a simple GET on /v2/_catalog in docker's distribution, so anyone can easily get a list of availables images in the registry...).

Is it possible to force a valid authentication before sending a token?

Here's our rake portus:info 
`[Mailer config] Host:     ****REMOVED****
[Mailer config] Protocol: https://

Portus version: 2.2.0
Portus has evaluated the following configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: true
ldap:
  enabled: true
  hostname: ****REMOVED****
  port: 389
  method: plain
  base: ****REMOVED****
  filter: ''
  uid: sAMAccountName
  authentication:
    enabled: true
    bind_dn: ****REMOVED****
    password: "****"
  guess_email:
    enabled: true
    attr: mail
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 3600
  catalog_page:
    value: 100
machine_fqdn:
  value: ****REMOVED****
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  manage_team:
    enabled: true
  manage_namespace:
    enabled: true
`

We host our application in a simple docker host, with Portus and the registry behind a Nginx reverse-proxy.

**Comment by mssola** [comment]
This is most probably a `cconfig` bug that we fixed. Re-open this if you are still having problems.

**Comment by PierrickMarchand** [comment]
@mssola, this issue is still present. Get https://registry/v2/token always returns a token (without any claim associated - obvisously). Tried with local auth and ldap auth, same result.

Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    keep_latest: 5
    tag: ''
ldap:
  enabled: true
  hostname: **REMOVED**
  port: 389
  timeout: 5
  encryption:
    method: Start_TLS
    options:
      ca_file: **REMOVED**
      ssl_version: TLSv1_2
  base: **REMOVED**
  admin_base: ''
  group_base: ''
  filter: ''
  uid: samaccountname
  authentication:
    enabled: true
    bind_dn: **REMOVED**
    password: "****"
  group_sync:
    enabled: true
    default_role: viewer
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: false
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  openid_connect:
    enabled: false
    issuer: ''
    identifier: ''
    secret: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 15
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: **REMOVED**
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  per_page: 10
