### ISSUE TITLE
When i try to visit the website,i get some errors.My OS is CentOS7

### ISSUE THREAD

**Issue by Shooting1007** [SUSE/Portus#1365]
![image](https://user-images.githubusercontent.com/17960727/28904040-cd95cdb0-783a-11e7-88f5-64c4abf0596d.png)

This is my docker info:
![image](https://user-images.githubusercontent.com/17960727/28904080-13980bde-783b-11e7-9aa9-8305a6a647d0.png)

**Comment by mssola** [comment]
How are you deploying this ? I assume it's a container-based deployment, but are you using an example from this repo ? is it a production environment, or development? Are you using a reverse-proxy ?

Just saying because this is a problem in an asset which usually means that there's something missing in the deployment:

If you used the `RAILS_SERVE_STATIC_FILES` environment variable, then the reverse-proxy configuration should handle the `/assets` path and proxy to Portus directly, instead of serving the asset the reverse-proxy. For example, for NGinx you could do something like:

```
    # https://portus is a defined upstream that points to your Portus instance
    location ~ ^/(assets)/ {
      proxy_pass https://portus;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_read_timeout 900;
      proxy_buffering on;

    }
```

If you are not using that variable, then the reverse-proxy should be serving the assets, in which case it should have mounted the static files (just as the `examples/compose/docker-compose.yml` is doing).

**Comment by mssola** [comment]
Closing this. If you have any more questions, feel free to leave more comments or write an email to our [mailing list](https://groups.google.com/forum/#!forum/portus-dev). Thanks!
