### ISSUE TITLE
Vulnerabilities no more displayed

### ISSUE THREAD

**Issue by superpoussin22** [SUSE/Portus#1378]
Last version with cconfig gem brake the vulenrabilities display in Portus  (but it display better some tags)

I see nothing in logs regarding clair

**Comment by mssola** [comment]
Agreed. There's something off. I'll investigate it whenever I can.

**Comment by mssola** [comment]
This should be fixed (notice that you have to use v2 of clair, as you can see on the `docker-compose.yml` file on the root of this project).

Also notice that this is now being done by the background process (see the `examples/compose` directory for some examples and how this `background` container can be used).

I won't close this issue for now, I'll wait for confirmation in the following days. Otherwise I'll mark it as fixed 😉 

Thanks for your patience!

**Comment by mssola** [comment]
Marking as fixed since the release is almost ready. This can go in a patch-level release if we discover that it's still affecting us. Thanks!
