### ISSUE TITLE
Not possible to create new namespaces when  Rack::Cache is enabled. 

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1414]
if Rack::Cache is enabled 

```rb
config.action_dispatch.rack_cache = true
```

then its not possible to create new namespaces.The error message is : **Name has already been taken**

originally discovered in #1406

**Comment by mssola** [comment]
Thanks for digging into this 👏

**Comment by mssola** [comment]
Scheduling this for 2.4. Looks like we forgot about this one :fearful: !

**Comment by mssola** [comment]
I can no longer reproduce this issue (we've changed how we create namespaces a bit, so that might have changed). Plus, Rack::Cache is not supported: you have to add the gem inside of the Gemfile, which we haven't done. If you want to have caching in place, consider using NGinx, varnish, squid, etc. instead.

Thanks for the feedback :+1:
