### ISSUE TITLE
portus 2.3.0 Sass::SyntaxError: File to import not found or unreadable: raleway

### ISSUE THREAD

**Issue by arno01** [SUSE/Portus#1415]
Dear Devs,

I am building a docker image using this Dockerfile https://github.com/openSUSE/docker-containers/blob/1f11a28efb0b2ea3d2701e32952192f728a1b0bb/derived_images/portus/Dockerfile

which installs ``http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/openSUSE_Leap_42.3/x86_64/portus-2.3.0~dev+git03e0e1181be24e02d6f764f3384422c22e6a299c-12.2.x86_64.rpm``

Once the container is started and I am trying to access the Portus, I am getting the following error in the browser:

```
Sass::SyntaxError: File to import not found or unreadable: raleway
```

Logs from the contaienr:

```
Started GET "/" for 10.38.0.10 at 2017-09-09 21:49:23 +0000
Processing by Auth::SessionsController#new as HTML
Redirected to https://portus.mysite.com/users/sign_up
Completed 302 Found in 3ms (ActiveRecord: 0.2ms)
Started GET "/users/sign_up" for 10.38.0.10 at 2017-09-09 21:49:23 +0000
Processing by Auth::RegistrationsController#new as HTML
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notification.html.slim (0.0ms)
  Rendered shared/_notifications.html.slim (0.6ms)
  Rendered devise/registrations/new.html.slim within layouts/authentication (2.3ms)
Completed 200 OK in 8ms (Views: 4.2ms | ActiveRecord: 0.4ms)
Started GET "/assets/application-19bb89953e189759801b157215cd5d67.css" for 10.38.0.10 at 2017-09-09 21:49:23 +0000
Started GET "/assets/webpack/application-4492ab55a430e53fa518.js" for 10.38.0.10 at 2017-09-09 21:49:23 +0000
Started GET "/assets/layout/portus-logo-login-page-e334348eeb5d33606a6c1c9903bfe633.png" for 10.38.0.10 at 2017-09-09 21:49:23 +0000

ActionController::RoutingError (No route matches [GET] "/assets/webpack/application-4492ab55a430e53fa518.js"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.16.0/lib/puma/configuration.rb:81:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
  vendor/bundle/ruby/2.1.0/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
  vendor/bundle/ruby/2.1.0/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
  vendor/bundle/ruby/2.1.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'


Processing by ErrorsController#show as */*
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (0.1ms)
  Rendered errors/_status_title.html.slim (0.1ms)
Completed 404 Not Found in 93ms (Views: 5.3ms | ActiveRecord: 0.0ms)
```

```
$ curl -L portus.mysite.com
... href="/assets/application-19bb89953e189759801b157215cd5d67.css" ...

$ curl -L portus.mysite.com/assets/application-19bb89953e189759801b157215cd5d67.css
...
          body:before {
            font-weight: bold;
            content: "\000a Sass::SyntaxError: File to import not found or unreadable: raleway.\000a Load paths:\000a   \002f srv\002f Portus\002f app\002f assets\002f images\000a...
...
```
To work this around, I had to comment these lines in the following files:

/srv/Portus/app/assets/stylesheets/application.scss
/srv/Portus/app/assets/stylesheets/core/variables.scss

```
// @import "raleway";
// @import "pacifico";
// @import "bootstrap-typeahead";
// @import 'lifeitup/lifeitup';
```

Nearest similar issue I have found is here https://github.com/rails/sass-rails/issues/139 , though not sure whether it is related.

Any ideas what is wrong? I was thinking gems need to be updated maybe...

Is there a working Docker image with Portus v2.3? (I would like to try the Clair integration)

Please let me know in case if you need more details.

Kind Regards,
Andrey Arapov

**Comment by arno01** [comment]
Looks like I was missing to set the ``RAILS_SERVE_STATIC_FILES: 'true'`` as per https://github.com/SUSE/Portus/blob/4e4329b08d4ffdd4ac52398fdee235b7a6620faf/examples/compose/docker-compose.yml#L26

Thanks @Evalle for pointing me to this :-)

I will give it a try and report in.

**Comment by arno01** [comment]
That is it, everything is working like a charm :-)

Thank you.

**Comment by NRagnarok** [comment]
Hello,
I reopen the issue because it seems that de opensuse/portus:head have the same problem...

I used the docker-compose.yml [here](https://github.com/SUSE/Portus/tree/master/examples/compose) to bring up Port.us on my server... 

But I get this with portus :

`Started GET "/users/sign_up" for 172.18.0.6 at 2019-02-13 21:57:10 +0000
Processing by Auth::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.slim within layouts/authentication
  Rendering shared/_notification.html.slim
  Rendered shared/_notification.html.slim (63.7ms)
  Rendering shared/_notification.html.slim
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (90.5ms)
  Rendered devise/registrations/new.html.slim within layouts/authentication (822.8ms)
Completed 500 Internal Server Error in 882ms (ActiveRecord: 3.6ms)

ActionView::Template::Error (Error: File to import not found or unreadable: raleway.
        on line 3 of app/assets/stylesheets/application.scss
>> @import "raleway";

   ^
):
    3:     .col-md-4.col-sm-2.col-xs-1
    4:     .col-md-4.col-sm-8.col-xs-10.text-center
    5:       = render 'shared/notifications'
    6:       = image_tag 'layout/portus-logo-login-page.png', class: 'login-picture'
    7:       = form_for(resource, as: resource_name, url: { action: 'create' }, :html => {:autocomplete => "off"}) do |f|
    8:         = f.text_field :username, class: 'form-control input-lg', placeholder: 'Username', required: true, autofocus: true
    9:         = f.email_field :email, class: 'form-control input-lg first', placeholder: 'Email', required: true

app/assets/stylesheets/application.scss:3
app/views/devise/registrations/new.html.slim:6:in `_app_views_devise_registrations_new_html_slim__1581882598849079740_70037293752060'
app/controllers/auth/registrations_controller.rb:22:in `new'
Processing by ErrorsController#show as HTML
  Parameters: {"status"=>"500"}
  Rendering errors/500.html.erb within layouts/errors
  Rendered errors/500.html.erb within layouts/errors (1.7ms)
Completed 500 Internal Server Error in 162ms (ActiveRecord: 0.0ms)
Error during failsafe response: Error: File to import not found or unreadable: raleway.
        on line 3 of app/assets/stylesheets/application.scss
>> @import "raleway";

   ^

  /srv/Portus/app/assets/stylesheets/application.scss:3
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc/engine.rb:49:in `render'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sassc-rails-2.1.0/lib/sassc/rails/template.rb:40:in `block in call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:171:in `module_include'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sassc-rails-2.1.0/lib/sassc/rails/template.rb:39:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:30:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:92:in `[]'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:355:in `find_asset'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:336:in `digest_path'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:325:in `asset_path'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:102:in `block in resolve_asset_path'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `each'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `detect'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `resolve_asset'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:101:in `resolve_asset_path'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/helpers/asset_url_helper.rb:200:in `asset_path'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/helpers/asset_url_helper.rb:345:in `stylesheet_path'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/helpers/asset_tag_helper.rb:143:in `block in stylesheet_link_tag'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/helpers/asset_tag_helper.rb:142:in `map'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/helpers/asset_tag_helper.rb:142:in `stylesheet_link_tag'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:185:in `block in stylesheet_link_tag'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:183:in `map'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:183:in `stylesheet_link_tag'
  /srv/Portus/app/views/layouts/errors.html.slim:5:in `_app_views_layouts_errors_html_slim___979338091715720983_49421640'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/template.rb:159:in `block in render'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/template.rb:354:in `instrument_render_template'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/template.rb:157:in `render'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/renderer/template_renderer.rb:16:in `render'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/renderer/renderer.rb:44:in `render_template'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/renderer/renderer.rb:25:in `render'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/rendering.rb:103:in `_render_template'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/streaming.rb:219:in `_render_template'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/rendering.rb:84:in `render_to_body'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/rendering.rb:25:in `render'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:36:in `render'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  /usr/lib64/ruby/2.5.0/benchmark.rb:308:in `realtime'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/benchmark.rb:14:in `ms'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:45:in `render'
  /srv/Portus/app/controllers/errors_controller.rb:17:in `show'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:194:in `process_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:132:in `run_callbacks'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:134:in `process'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/rendering.rb:32:in `process'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal.rb:191:in `dispatch'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal.rb:252:in `dispatch'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `each'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `serve'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:840:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:38:in `call_app'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `block in call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:28:in `tagged'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `tagged'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:524:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/urlmap.rb:68:in `block in call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `each'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
`

Any idea ?

Thank you
