### ISSUE TITLE
must ssl？

### ISSUE THREAD

**Issue by niuhp** [SUSE/Portus#1430]
i don’ want use https to visit portus，how can i config？？i run portus with docker-compose.insecure.yml of the master branch

when i visit the addr，i get

Please review your configuration
SSL
For security reasons you need to use SSL. SSL is not configured, please review your server configuration.

**Comment by mssola** [comment]
This is because the `check_ssl_usage` config option is enabled by default (see the [the documentation](http://port.us.org/docs/Configuring-Portus.html#enforce-ssl-usage-on-production)). In your case, it should be a matter of setting the following env. variable: `PORTUS_CHECK_SSL_USAGE_ENABLED` to false.

That being said, for these kinds of questions you can use our [mailing list](https://groups.google.com/forum/#!forum/portus-dev) instead.

I'm going to close this issue, but feel free to ask more questions here if you have more doubts in this regard.
