### ISSUE TITLE
SSMTP support 

### ISSUE THREAD

**Issue by reysillo** [SUSE/Portus#1440]
Please add SMTPS for Portus Email Options

**Comment by mssola** [comment]
Could you elaborate on this ? Isn't that already possible with Portus ?

**Comment by reysillo** [comment]
Thanks, please check https://en.wikipedia.org/wiki/SMTPS, I use a smtp provider that requires to activate SSL option on 465 port. I can't find a way to setup SSL active on current Portus configuration options

**Comment by mssola** [comment]
The title says SSMTP but then in your second commend you mention SMTPS, I guess it's the later 😕  ?

For the port, you have the the `email.smtp.port` configuration option. Moreover, for SSL, we have the `enable_starttls_auto` set to true if you provide the `email.smtp.user_name` configuration option. The only thing missing that we can configure from Rails' side is `openssl_verify_mode`, and I believe it takes the default `:peer` option, so that should be fine.

Isn't this what you need ?

**Comment by Vad1mo** [comment]
We use postmarkapp that supports SMTP with SSL/TLS or as you say SMTPS. 

It works fine, make sure you have the latest ca-certs installed.

**Comment by mssola** [comment]
Closing since it's been stale.
