### ISSUE TITLE
No "latest" docker tag present on docker hub

### ISSUE THREAD

**Issue by r-chris** [SUSE/Portus#1529]
Hi,

I'm not sure if this is intentional, but the `opensuse/portus` docker image on docker hub does not have a `latest` tag at present. Hence, I can't easily pull the latest image. There is a `head` tag - are people supposed to use that instead?

Thank you!

**Comment by jcgruenhage** [comment]
The example files at https://github.com/SUSE/Portus/tree/master/examples/compose use the head tag, so I guess that's the one to use.

**Comment by r-chris** [comment]
I would suggest adding a `latest` to point to the latest **stable** release and `head` is probably the current bleeding edge release ?

**Comment by mssola** [comment]
We didn't have a `latest` tag because that word has a different meaning to different people: latest as in latest stable release, or latest as in master ?

After some time, I think it would be a good thing to point to the latest stable release. Furthermore, I'd like to add another tag: `development`, or something like that. That's because `head` was broken for quite some time and people could simply use the Dockerfile from the root of the project just fine. So, `development` would simply be a build from the root of the project on the master branch.

What do you think ?

**Comment by r-chris** [comment]
Generally, if I do a `docker pull XYZ:latest` I expect to get something that will work. If there are unstable releases on docker hub, they probably shouldn't be tagged as `latest`

Having a `dev` tag certainly makes sense for people to know this isn't a `stable` release.

**Comment by vitoravelino** [comment]
`latest` for stable, `dev` or `head` to master branch (I'm tend to prefer `head` but I'm not sure if people would understand that this might be an unstable version). 

Which terms do people usually use in the docker world?

**Comment by mssola** [comment]
@vitoravelino note that `dev` and `head` would be the master branch but from two different sources:

- `dev` for what we've got in Github.
- `head` for what we produce on OBS when fetching the master branch from Github.

> Generally, if I do a docker pull XYZ:latest I expect to get something that will work. If there are unstable > releases on docker hub, they probably shouldn't be tagged as latest
>
> Having a dev tag certainly makes sense for people to know this isn't a stable release.

Let's do that 👍

**Comment by mssola** [comment]
Current state:

- [x] Add a `latest` tag.
- [x] Remove old tags (2.0 and 2.1).
- [ ] Add a `development` tag.
- [ ] Documentation: improve the README, the `gh-pages` branch, etc. It should be crystal clear where to fetch each version, how to deploy it, etc.

The `development` tag is kind of tricky because you cannot specify multiple source repositories for automated builds on Docker Hub. I'll probably add a `SUSE/portus` image which only includes the `development` tag (while pointing to the right production-ready images).

**Comment by mssola** [comment]
I think we can leave the `development` tag for another time (#1544)
