### ISSUE TITLE
Use docker image with Postgresql

### ISSUE THREAD

**Issue by jcgruenhage** [SUSE/Portus#1530]
I've just tried setting up portus with postgresql database, and realized that the docker image does ship a different database config file, which doesn't allow setting the adapter and expects different env variables than the `database.yml` file in this repository. While this is not that really bad (I'll just pass through my own `database.yml`) it is pretty confusing, as it behaves differently than what is described in http://port.us.org/docs/database.html

**Comment by jcgruenhage** [comment]
Actually, this is bad. The pg gem is not bundled in the docker container (anymore?), so it won't run with a passed through `database.yml`.

From the docs linked above:
> Note that these dependencies have already been bundled in the official Portus image.

So this again is in conflict with the official documentation.

**Comment by zot24** [comment]
They don't fully support Postgres yet you have to use MySQL until they sort it out there are few issues explaining why, I'm waiting for this feature as well as atm I have MySQL (for Portus) and Postgres (for Clair) running and it will be mint to have just one DB 👍

**Comment by jcgruenhage** [comment]
@zot24 thanks for the info, but that should still be communicated in the documentation then :D

**Comment by mssola** [comment]
@jcgruenhage this is due to a bug: #1418. Once we fix this (which should happen as soon as possible), you'll be able to interact with the database adapter as documented 😅 

> I'm waiting for this feature as well as atm I have MySQL (for Portus) and Postgres (for Clair) running and it will be mint to have just one DB

See #1499 😉 It's a breaking change (e.g. we'd have to provide a migrator from mysql to postgresql data) and we were short in time. Feel free to leave a comment in #1499 if you have any suggestions on the topic 😃 

Closing this now since it's already tracked in #1418, but feel free to submit new comments here if you have more doubts 😉
