### ISSUE TITLE
Restart the mirror data to be cleared

### ISSUE THREAD

**Issue by nunterr** [SUSE/Portus#1540]
Image installation of Portus, after use, restart mirroring, all previous user data is cleared, please ask what needs to be configured to save data

**Comment by mssola** [comment]
What are you doing exactly to deploy Portus ? Could you be more specific ? I'm a bit lost 😕

**Comment by nunterr** [comment]
The master version I used, docker-compose up deployment, was emptied when the service was restarted during use @mssola

**Comment by vitoravelino** [comment]
@nunterr I suppose you are using the `docker-compose.yaml` from the root folder, right?

Based on that I guess what he's saying is that every time he shut down and start Portus via docker-compose, the previous data is not there anymore. That is happening because we `rake db:migrate:reset` inside the init bash script.

@mssola Btw, why do we need that bash file? Just to wait until the database is ready to start puma? Is that the only reason? Maybe we could change it to another command to avoid the reset of the database? I guess if the developer wants to erase the database, he could recreate the db container?

**Comment by mssola** [comment]
@vitoravelino you are right. Now notice that in the `bin/background.rb` we are also waiting for the DB to be up. Maybe we can re-use part of the initialization code there in the development procedure, output some help message (as in, if it's the first time you have to call "blabla") and then call puma.

What do you think ?

@nunterr is this what you are saying ?

**Comment by vitoravelino** [comment]
@nunterr We merged #1561 today but we are still not sure if that's the case for you. Let us know if that fixed your issue for development.

**Comment by mssola** [comment]
As @vitoravelino said, #1561 should've done the trick, so I'll close this issue. If this is not the case for you, feel free to open it again and leave more comments 😉 Thanks!
