### ISSUE TITLE
Too complicated to use

### ISSUE THREAD

**Issue by lanmingle** [SUSE/Portus#1542]
Why not provide a built-in database?

docker run --rm -it opensuse/portus:2.2 ok ?

**Comment by Vad1mo** [comment]
Portus follows the common practice to run a single application per  container. That what the main purpose of Docker is. 

You can find many sources on the net
Eg. https://developers.redhat.com/blog/2016/02/24/10-things-to-avoid-in-docker-containers/

**Comment by lanmingle** [comment]
@Vad1mo 

你好，我不是菜鸟，我就是觉得 Portus 不能一条命令运行起来，如： nexus 3 提供的 docker ，单纯使用一条命令即运行起来，明白我的意思没有？

Hello, I'm not a rookie, I just don't think Portus can run a single command, such as the docker provided by nexus 3, and just use a single command to run it, and understand what I mean?

**Comment by Vad1mo** [comment]
典型的** Container Registry **应用程序由许多不同的进程/应用程序组成。 Portus WebUI，Docker Registry，PortusCtl，Clair，最后是DB，它通常是一个共享实例。

将数据库放入与Portus WebUI相同的容器中并不会产生太大的变化，但会使维护变得更加困难。 你不这么认为吗？


The typical **Container Registry** application is made up of many different processes/applications. The Portus WebUI, Docker Registry, PortusCtl, Clair and finally the DB, which is often a shared instance anyway.

So Putting the DB into the same container as Portus WebUI would not make much of a difference, but would make it more difficult to maintain. Don't you think so?

**Comment by mssola** [comment]
I have to admit that I'm not acquainted with the architecture of Nexus, but last time I looked into it, it looks like they provide their own implementation of the registry. We decided to follow another route: simply using the provided and stable API from the upstream project. For us it is better to do this because:

- People already using a Docker registry can then add Portus as an additional layer.
- There is a clear separation of concerns: the Docker registry (docker-distribution) stores the contents, and Portus is a layer on top of it providing authentication and authorization (and a bunch of other management utilities).

Separating concerns like that was a better use case in our understanding, since then people can deploy components in a more microservices-friendly way. You could have *everything* into a single container, but then you'd be effectively re-creating a monolith (in a non-intuitive way if I may add). For example, if you discover that the DB is your bottleneck, and not portus, you can simply scale up the DB service and leave portus alone (which is common practice if you are using container orchestrators like Docker Swarm or Kubernetes). The same for the different services orbiting around a typical Portus installation.

That being said, the downside is maybe that running a single `docker run` command is of course easier (even though I'd then debate whether doing that is desirable at all in a production environment...). We prefer the freedom that separating concerns properly leaves to system administrators to arrange a typical Portus application as they see fit. On the other hand, we are working on making things easier (see our `examples` directory, or [this Helm chart](https://github.com/kubic-project/caasp-services/tree/master/contrib/helm-charts/portus) for Kubernetes), so all feedback is welcomed.

Finally, I'll close this issue because issues are meant for discussing bugs, features, etc. For general discussions we can rely on the [mailing list](https://groups.google.com/forum/#!forum/portus-dev).
