### ISSUE TITLE
Broken master branch

### ISSUE THREAD

**Issue by bernisands** [SUSE/Portus#1555]
Hello,
i have cloned the master branche to do a bare metal install.
But i have seen, that there a least two problems:
First in the gem file there is no crono anymore.
Second, in different files like mail.rb and namespace_validator.rb
i get an error 
NoMethodError (undefined method `match?' for "portus_global_namespace_1":String
Did you mean?  match):
I have corrected match? in match and now it works. But i don´t know what other errors are in the code.
So my question is: Which Version/Branch should i use to get a working BareMetal installation?

regards 
Bernd Sandmann

**Comment by mssola** [comment]
> First in the gem file there is no crono anymore.

That's because we have removed crono, you should use `bin/background.rb` now 😉 That's something that we have to document.

> NoMethodError (undefined method `match?' for "portus_global_namespace_1":String
Did you mean? match):

The required version of Ruby is 2.4, and in this version the `#match?` method exists (it didn't before). You have to upgrade your ruby. Maybe we can add a check when initializing portus for this :thinking:

Do you need more info ?

**Comment by mssola** [comment]
- For the documentation part, I've added #1567.
- For the checks on the ruby version, I've just submitted #1568.

**Comment by mssola** [comment]
I think we can close this issue. If you have any more doubts on this issue feel free to add more comments 👍 Thanks!
