### ISSUE TITLE
Not possible to create js in production mode

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1616]
Its not possible to create webpack modules in production mode as needed.

```
export NODE_ENV=production
yarn --no-emoji --no-progress
rake portus:assets:compile
```
causes:
```
resolve 'babel-loader' in '/app/app/assets/javascripts'
  Parsed request is a module
  using description file: /app/package.json (relative path: ./app/assets/javascripts)
  after using description file: /app/package.json (relative path: ./app/assets/javascripts)
    resolve as module
      /app/app/assets/javascripts/node_modules doesn't exist or is not a directory
      /app/app/assets/node_modules doesn't exist or is not a directory
      /app/app/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /app/node_modules
        using description file: /app/package.json (relative path: ./node_modules)
        after using description file: /app/package.json (relative path: ./node_modules)
          using description file: /app/package.json (relative path: ./node_modules/babel-loader)
            as directory
              /app/node_modules/babel-loader doesn't exist
            no extension
              /app/node_modules/babel-loader doesn't exist
            .js
              /app/node_modules/babel-loader.js doesn't exist
            .json
              /app/node_modules/babel-loader.json doesn't exist
rake aborted!
```

**Comment by mssola** [comment]
This is kind of similar to [this](https://github.com/SUSE/Portus/issues/1612#issuecomment-360177917), no ?

**Comment by Vad1mo** [comment]
yes its related.

**Comment by mssola** [comment]
Sorry for taking too long to give you a proper answer, I was busy with more high-priority tasks.

The idea (and this applies to #1611 and #1612 too), is that both the RPM and the Docker image (which simply installs this RPM) are ready to be used, so they exclude a bunch of stuff which is not needed in production for reducing the size of the final Docker image. For example, the `node_modules` directory is removed from the final file system, as it's not needed for production (what production will use are the public assets build from this `node_modules` directory). Moreover, on this, topic, notice that you are setting `NODE_ENV=production`. This means that the `devDependencies` from `package.json` won't be downloaded (which is what the error you pasted is saying). Another example of this are the gems. We only install those related to production usage. That's why you are facing #1612. If you want more info, take a look at our final [portus.spec file](https://build.opensuse.org/package/view_file/Virtualization:containers:Portus:2.3/portus/portus.spec?expand=1).

So, this is all done on purpose: it's intended behavior. You should not have to deal with building gems, JS dependencies, etc.; the docker image should have everything bundled for you, so you only need to pull this image and run it.

To be honest, I don't know why you'd want to do all this (as in, I don't understand the use case). The only possible use case is to add your own CSS code to customize further the UI (which is something that could be provided in future releases). Other than that, I don't know why you'd want to go through all these steps. Is there something from the code you are missing ? Is the entrypoint script missing a piece of code you'd like to add ?

**Comment by mssola** [comment]
Moreover, if you are building your own custom image as you are mentioning in #1611, I wouldn't advise to take the production Docker image as a base. Instead, I'd reproduce what we are doing in the [portus.spec](https://build.opensuse.org/package/view_file/Virtualization:containers:Portus:2.3/portus/portus.spec?expand=1) in a build script or in a custom Dockerfile with the source code of Portus. Otherwise you are going to face all the issues you mentioned.

So, we could either add the workflow you wanted to establish into our pipeline (as in, maybe you are just missing a piece of code or workflow that we could perfectly add to our build system or code), or you will have to fetch our build scripts and adapt them to your needs.

**Comment by mssola** [comment]
@Vad1mo would you agree to close this issue as well ?

**Comment by Vad1mo** [comment]
thx for the details Explantation. We are building our custom image (multi-stage) because we are have to change some functionality and actually make it run in production.
The point is that we follow a different workflow. We don't build the RPM externally and just pack them in  the container, we build the container from the source code.

This is the reason the workflow don't match. However now have adapted the workflow so we are fine now.

**Comment by mssola** [comment]
> This is the reason the workflow don't match. However now have adapted the workflow so we are fine now.

I see. Well, if we can do something to improve this situation from Portus just submit an issue 😉
