### ISSUE TITLE
Portus docker-compose confusion

### ISSUE THREAD

**Issue by hactar** [SUSE/Portus#1617]
I'm trying to fire up Portus in containers, however this is proving to be difficult, and the documentation is confusing:

There are multiple docker-compose files in this registry:

1) The one in the root folder, using the :development tags
2) Two in the examples/compose folder
3) The others in the example folder

There's multiple documentation pages on this too, they contain similar, but not identical information:

1) https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment
2) http://port.us.org/docs/setups/2_containerized.html

https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment describes 5 containers that the docker-compose file is supposed to create: portus, db, registry, webpack and crono. This does not match any of the docker-compose files:

- root folder docker-compose generates: portus, background, webpack, clair, db, postgres, registry
- examples/compose generate: similar ones to root, but with some variations.

None create **crono**, I assume **crono** is now **background**, but as I'm new to portus I'm not sure.

It would be great if someone that knows Portus could:
- Update the documentation pages and sync them
- For each of the provided compose files, provide exactly what is missing to actually launch the containers. I for example tried firing up examples/compose/docker-compose.insecure.yml and had it fail on me due to missing config.yml and /secrets/portus.crt files. Maybe I was running it from the wrong folder, maybe I have to place these files from somewhere to somewhere, but these steps aren't documented. Simply downloading docker-compose.insecure.yml and the .env file, and updating these with correct values does not work as the documentation would suggest.

**Comment by mssola** [comment]
Hi, we have two docker-compose kinds of setups:

1. The one on the root of the project is for development purposes only. It's the one documented on the wiki. I've just updated the wiki with the other containers (they were added quite recently and it seems that we forgot about the wiki...).
2. The production-ready examples inside of the `examples` directory have a README.md file which documents what you are supposed to do in order to deploy them. It also specifies . These are examples, so you should be aware that you might want to change them to suit your needs (although the certificates part is documented, but maybe it can be improved?).

**Comment by mssola** [comment]
This has already been done. The documentation reflects better this situation and the wiki has also been updated. Hopefully it's all clearer :+1:
