### ISSUE TITLE
Cannot build Portus Image: "update-alternatives: error: alternative path /usr/bin/bundle.ruby2.5 doesn't exist"

### ISSUE THREAD

**Issue by tomthetommy** [SUSE/Portus#1620]
So I'm still having no luck in building an image from the master branch. I haven't been able to get an image built in about 2 weeks now.

When I run the build on the following file I get an error (update-alternatives: error: alternative path /usr/bin/bundle.ruby2.5 doesn't exist):

```
FROM opensuse/ruby:2.5
MAINTAINER SUSE Containers Team <containers@suse.com>

ENV COMPOSE=1
EXPOSE 3000

WORKDIR /srv/Portus
COPY Gemfile* ./

# Let's explain this RUN command:
#   1. First of all we refresh, since opensuse/ruby does a zypper clean -a in
#      the end.
#   2. Then we install dev. dependencies and the devel_basis pattern (used for
#      building stuff like nokogiri). With that we can run bundle install.
#   3. We then proceed to remove unneeded clutter: first we remove some packages
#      installed with the devel_basis pattern, and finally we zypper clean -a.
RUN zypper ref && \
    zypper -n in --no-recommends ruby2.5-devel \
           libxml2-devel nodejs libmysqlclient-devel postgresql-devel libxslt1 && \
    zypper -n in --no-recommends -t pattern devel_basis && \
    gem install bundler --no-ri --no-rdoc -v 1.15.4 && \
    update-alternatives --install /usr/bin/bundle bundle /usr/bin/bundle.ruby2.5 3 && \
    update-alternatives --install /usr/bin/bundler bundler /usr/bin/bundler.ruby2.5 3 && \
    bundle install --retry=3 && \
    zypper -n rm wicked wicked-service autoconf automake \
           binutils bison cpp cvs flex gdbm-devel gettext-tools \
           libtool m4 make makeinfo && \
    zypper clean -a

ADD . . `
```

**Comment by tomthetommy** [comment]
Also when using the examples in the Portus/examples/compose directory also lead to failures:

This one from the opensuse/portus:head image, and compose_background_1 container:

> bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)


And this from the opensuse/portus:head and compose_portus_1 container:

> rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails: DROP TABLE `namespaces` CASCADE

**Comment by mssola** [comment]
Just to be sure, remove first `opensuse/ruby:2.5` and other old portus' images and pull them again, since updates have been issued and I at least cannot reproduce this.

**Comment by branzo** [comment]
Hello @mssola, 

i got the same error today, after pulling opensuse/portus:head from hub.docker.com, here's an extract from the logs:

portus_1    | Initializing database
portus_1    | portus_production already exists
portus_1    | No smtp username supplied, not using smtp authentication
portus_1    | [Mailer config] Host:     my.host.name
portus_1    | [Mailer config] Protocol: https://
portus_1    | -- create_table("activities", {:force=>:cascade})
portus_1    |    -> 0.1132s
portus_1    | -- add_index("activities", ["key"], {:name=>"index_activities_on_key", :using=>:btree})
portus_1    |    -> 0.0598s
portus_1    | -- add_index("activities", ["owner_id", "owner_type"], {:name=>"index_activities_on_owner_id_and_owner_type", :using=>:btree})
portus_1    |    -> 0.0497s
portus_1    | -- add_index("activities", ["recipient_id", "recipient_type"], {:name=>"index_activities_on_recipient_id_and_recipient_type", :using=>:btree})
portus_1    |    -> 0.0504s
portus_1    | -- add_index("activities", ["trackable_id", "trackable_type"], {:name=>"index_activities_on_trackable_id_and_trackable_type", :using=>:btree})
portus_1    |    -> 0.0509s
portus_1    | -- add_index("activities", ["trackable_type"], {:name=>"index_activities_on_trackable_type", :using=>:btree})
portus_1    |    -> 0.0514s
portus_1    | -- create_table("application_tokens", {:force=>:cascade})
portus_1    |    -> 0.1554s
portus_1    | -- add_index("application_tokens", ["user_id"], {:name=>"index_application_tokens_on_user_id", :using=>:btree})
portus_1    |    -> 0.0511s
portus_1    | -- create_table("comments", {:force=>:cascade})
portus_1    |    -> 0.1346s
portus_1    | -- add_index("comments", ["repository_id"], {:name=>"index_comments_on_repository_id", :using=>:btree})
portus_1    |    -> 0.0496s
portus_1    | -- add_index("comments", ["user_id"], {:name=>"index_comments_on_user_id", :using=>:btree})
portus_1    |    -> 0.0487s
portus_1    | -- create_table("namespaces", {:force=>:cascade})
portus_1    | rake aborted!
portus_1    | ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails: DROP TABLE `namespaces` CASCADE
[...]
portus_1    | Caused by:
portus_1    | Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:510:in `drop_table'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/schema_statements.rb:219:in `create_table'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:482:in `create_table'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:665:in `block in method_missing'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `block in say_with_time'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `say_with_time'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:654:in `method_missing'
portus_1    | /srv/Portus/db/schema.rb:55:in `block in <top (required)>'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/schema.rb:41:in `instance_eval'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/schema.rb:41:in `define'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/schema.rb:61:in `define'
portus_1    | /srv/Portus/db/schema.rb:14:in `<top (required)>'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:221:in `load_schema_for'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:238:in `block in load_schema_current'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:278:in `block in each_current_configuration'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:277:in `each'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:277:in `each_current_configuration'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:237:in `load_schema_current'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:237:in `block (3 levels) in <top (required)>'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:241:in `block (3 levels) in <top (required)>'
portus_1    | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
portus_1    | Tasks: TOP => db:schema:load
portus_1    | (See full trace by running task with --trace)
portus_1    | bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)
portus_1    | RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rake db:setup
portus_1    |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
portus_1    |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
portus_1    |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
portus_1    |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
portus_1    |   /srv/Portus/packaging/suse/portusctl/lib/cli.rb:258:in `exec'
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
portus_1    |   packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'
portus_1    | Error at setup time

let me know if you need some more infos..

**Comment by vitoravelino** [comment]
@branzo Did you remove the old images locally before trying again? I got a similar error in the past and rerunning everything from scratch worked.

**Comment by branzo** [comment]
@vitoravelino 

sorry, but how could that help solving the problem? I'm not trying to build the image myself so i should not experience caching (or common layers problems) if the images are built correctly (or am i missing something at this point?).

anyway, removing old portus images and repulling them did not help to solve the problem.

**Comment by fentas** [comment]
Get the same error. Also tried re-pulling images.
For me, I had portus running for 3 Month now (on `:head`, without restarting it).
I could imagine that I jumped from `2.1` directly to `2.3`. Maybe this is a migration error. At least for me?

I also did a `rake db:migrate`

```sh
sh-4.3# portusctl exec rake db:migrate
[Mailer config] Host:     ***
[Mailer config] Protocol: https://
Migrating to AddOmniauthToUsers (20170630194953)
== 20170630194953 AddOmniauthToUsers: migrating ===============================
-- add_column(:users, :provider, :string)
   -> 1.1608s
-- add_column(:users, :uid, :string)
   -> 0.8027s
== 20170630194953 AddOmniauthToUsers: migrated (1.9637s) ======================

Migrating to RemoveFulltextIndexRepositoriesOnNameIndex (20171011150408)
== 20171011150408 RemoveFulltextIndexRepositoriesOnNameIndex: migrating =======
-- index_exists?(:repositories, :name, {:name=>"fulltext_index_repositories_on_name"})
   -> 0.0008s
-- remove_index(:repositories, {:name=>"fulltext_index_repositories_on_name"})
   -> 0.4256s
-- index_exists?(:namespaces, :name, {:name=>"fulltext_index_namespaces_on_name"})
   -> 0.0011s
-- remove_index(:namespaces, {:name=>"fulltext_index_namespaces_on_name"})
   -> 0.4796s
== 20171011150408 RemoveFulltextIndexRepositoriesOnNameIndex: migrated (0.9074s) 

Migrating to AddIndexesToActivities (20171014192702)
== 20171014192702 AddIndexesToActivities: migrating ===========================
-- add_index(:activities, [:trackable_type])
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Index name 'index_activities_on_trackable_type' on table 'activities' already exists
```

But still the same error.

**Comment by branzo** [comment]
@fentas 

thanks for the feedback. Let's see what @mssola thinks about this new infos?

**Comment by mssola** [comment]
So, I think we are talking here about multiple different issues. Let's see if I can clarify things (hopefully I'm not missing anything 😋).

First of all, I cannot reproduce the issue on the first comment. This may have been a hiccup on the `opensuse/ruby:2.5` docker image. We had some issues when introducing this image but we've rolled out a solution. Just to be sure, this is what I performed on the root of the project (current master):

```
$ docker rmi -f opensuse/ruby:2.5 opensuse/portus:development
$ docker-compose build   # this should've been troublesome according to your first message...
$ docker-compose up
```

The second issue is:

> This one from the opensuse/portus:head image, and compose_background_1 container:
>>    bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)

This is most surely an old issue from the image. If you remove the image, pull it again (just to be sure it's the latest one), it should just work. That being said, just to be safe, try with the `2.3` tag (and remove an old version if needed).

The third issue is:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails: DROP TABLE `namespaces` CASCADE
```

I was able to reproduce this some weeks ago, but not anymore (I've messed with the database as much as possible). Is there a way to reliably reproduce this ?

**Comment by branzo** [comment]
Hello @mssola, 

thanks for the clarifications. 

Do you prefer that we continue with the ActiveRecord stuff using a new issue?

**Comment by mssola** [comment]
> Do you prefer that we continue with the ActiveRecord stuff using a new issue?

It would be better, yes. Could also detail how to reproduce this ?

**Comment by mssola** [comment]
This can be closed then. If you still face this issue, simply remove your image and pull it again just to be sure you are on the latest version of the tag.
