### ISSUE TITLE
Better organizing of issues and releases

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1659]
I am proposing to enable the [projects](https://github.com/SUSE/Portus/projects) feature of GitHub for this project. This would allow the community what still needs to be done or is still unfinished for the upcoming release. 

This would add transparency and better steering of the project. I can also voluntier and contribute by organizing the issues add adding order to them.

**Comment by mssola** [comment]
This is something that we considered when this feature was introduced. We decided to not go for it since we (at SUSE internally) already have our own Trello board for managing the different tasks.

That being said, since we are getting more contributions from the community, it's true that it makes sense to open this part too. I've never tried the projects feature of Github, so it could go terribly wrong, but maybe it's worth a shot.

@vitoravelino what do you think about trying it for the 2.4 release ? (it would be a very simple kanban kind of workflow: "to do", "doing" and "done").

**Comment by vitoravelino** [comment]
I think it's a good idea because to gives the community an idea of what's going on. People don't know what's currently being done in the milestone page unless we add a label, which is not ideal. Having columns make things easier. 

Everything is an issue there, so I guess we won't have any trouble.

**Comment by mssola** [comment]
I've just created a board for 2.3 and 2.4 👍 Thanks for the suggestion.
