### ISSUE TITLE
Background Process should not delete the whole registry and ad it again.

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1664]
The Background process should not mess up the Portus DB. 
Because sometime when the registry isn't available for a short moment the background job removes all the images from Portus. It then adds them all again. This is problem as the audit trail is changed and all the users and timestamps are gone.

Therefore I propose to add the option to the Background to not delete images, unless specified otherwise.  
We should also make the background process more resilient and tolerate errors from clair, registry and portus and not shutdown or messup the Portus DB. 

The issue partly #1665 addresses this topic as well.  

#1631 Will reduce the problem a bit, but still it should be possible to do a maybe one way sync registry->portus). 

This also raises the question why should there be a sync? If you push then Portus should be available otherwise auth won't work. If Portus is down for a brief moment the Registry will  retry event notifications?

The only reason I see when sync is needed, is when you connect a new registry to portus. In this case you would like to import the images. This is not a common case.

**Comment by mssola** [comment]
> We should also make the background process more resilient and tolerate errors from clair, registry and portus and not shutdown or messup the Portus DB.

Sure. We already catch a lot of situations where the registry is behaving funny, but we are still missing some corner cases...

> This also raises the question why should there be a sync? If you push then Portus should be available otherwise auth won't work. If Portus is down for a brief moment the Registry will retry event notifications?

Agreed. The `sync` idea was introduced in the very beginning of Portus, and it was proposed with lots of good intentions, but it turned out to be a can of worms: it brings more problems than it solves. So, together with #1631, I propose the following configuration for the sync:

```yaml
background:
  registry:
    enabled: true
  sync:
    enabled: false
    when: onstartempty
    delete: false
```

So, the `sync` task will be disabled by default, since as you point out it will be rarely needed. But, if people really want to use it, then they have two more options:

- `delete`: `false` by default which means that the task won't delete anything. Set to true if you want this task to delete unreferenced repositories.
- `when`: only works if this task is enabled at all, and it has three possible values:
  - `always`: it will be executed every now and then as it's happening nowadays.
  - `onstart`: it will be executed when Portus starts.
  - `onstartempty`: this is the default and it will be executed when Portus starts and only if the DB is empty. This is the safest option, and the idea behind this is to only run this task when starting Portus for the first time.

I also propose to implement this for the 2.3 release, since we have already been flooded by these issues recently...

@Vad1mo @vitoravelino what do you think ?

**Comment by Vad1mo** [comment]
Very nice, 
I suggest a slight change in the syntax. I think is more developer friendly because of known concepts.


```yaml
background:
  registry:
    enabled: true
  sync:
    enabled: false
    sync-strategy: two-way | one-way | initial | on-start
```

- two-way: As it is now update and delete
- one-way: Only update Portus but don't delete
- initial: Only if Portus is empty do an full load (write to Portus only)
- on-start: On Portus start run once a two way sync.

The only use case that is not covered is `onstart no delete`, however I think its not really as its the same as one-way. Because why do you want to use `on-start no delete` only on start but not all the time the result is the same.

**Comment by mssola** [comment]
Sounds good to me. The default value would be `initial`, right ?

**Comment by Vad1mo** [comment]
Right now its `two-way` however I think `initial` would provide the best UX. 

Imagine you start portus for the first time with an  existing registry, you login the first time and 💥 🎉

**Comment by mssola** [comment]
> I also provided an alternative naming,

I like this better. It's more explicit.

**Comment by mssola** [comment]
See #1675.

**Comment by mssola** [comment]
>  If Portus is down for a brief moment the Registry will retry event notifications?

According to the [documentation](https://docs.docker.com/registry/notifications/), the registry should retry notifications if it failed.
