### ISSUE TITLE
examples/compose not working with images before 2.3

### ISSUE THREAD

**Issue by CodingSpiderFox** [SUSE/Portus#1673]
I wanted to set up an instance of portus using the example under examples/compose (with SSL)

When I changed to image references from opensuse/portus:head to opensuse/portus:2.2 and executed docker-compose down -v && docker-compose up, the containers cannot reach the database (see log attached)

Same for version 2.1

It works using the head or 2.3 docker image

[portuslog.txt](https://github.com/SUSE/Portus/files/1707128/portuslog.txt)

**Comment by Vad1mo** [comment]
2.2 and 2.3 are very different in their setups. (different compose file and components) its not possible to switch between them that easy.

**Comment by CodingSpiderFox** [comment]
So can I simply go back to a certain revision in the master and start 2.2 with the examples/compose setup from there? If so, which revision would you recommend?

**Comment by Vad1mo** [comment]
going back to tag will work.

I recommend to start using Portus 2.3 head for now

**Comment by CodingSpiderFox** [comment]
When I go to a tag, the examples directory is not there

**Comment by mssola** [comment]
@CodingSpiderFox that is done on purpose: the examples directory was introduced when developing 2.3 and they will only work for 2.3 onward. On git the 2.3 final release has not been tagged yet, so in order to get the `examples` directory you have to be either on the `master` or the `v2.3` branch.

Moreover, the `2.3` release should be released rather soon-ish, so I'd recommend using `opensuse/portus:2.3` since it should be pretty stable (there are some PRs like #1675 which should polish some stuff).

**Comment by mssola** [comment]
@CodingSpiderFox #1680 hopefully clarifies this situation. If you have more questions, feel free to write them on this issue (even if it's now closed 😉).
