### ISSUE TITLE
Is v2.3 safe to use for updates

### ISSUE THREAD

**Issue by hbastosc** [SUSE/Portus#1676]
I haven't found any documentation on how to upgrade from 2.2 and looking into the updates to 2.4 seems you will keep adding features and then start fixing bugs or is it just safe to use?

**Comment by Vad1mo** [comment]
Well, it should. However I would make a DB backup beforehand :) 
Right now the release is about to happen and quite stable except a few [minor issue](https://github.com/SUSE/Portus/projects). The main workflow operation should work fine.

To be on the safe side I would wait a few days more, it shouldn't take long.

**Comment by mssola** [comment]
@hbastosc we haven't updated the docs because we haven't released 2.3 yet (we just branched out 2.3 without actually tagging the release). The idea is that we are gathering feedback from the `2.3` image so we can release it with more confidence.

That being said, we have written down upgrade instructions [on this section of the changelog](https://github.com/SUSE/Portus/blob/master/CHANGELOG.md#upgrading). When we perform the final release we will also submit a blog post with this info.

The current 2.3 image should already be pretty safe, but if you really want to play safe, then I'd do as @Vad1mo recommended and wait for the final release. The idea for 2.4 is to keep polishing out known small issues and bring more features. I'd recommend using 2.3 instead of waiting for 2.4 if that's what you mean 😉 

Hope everything is clear 😃

**Comment by hbastosc** [comment]
Thanks for the documentation. Will wait for the release then. :)
