### ISSUE TITLE
Deploy on Raspberry?

### ISSUE THREAD

**Issue by DanielRamosAcosta** [SUSE/Portus#1678]
Is there any way to deploy it in a Raspberry? I've tried to dockerize the service for the RPI2 without succes. Are there any easy way to achieve this?

Thanks in advance!

**Comment by mssola** [comment]
Hi @DanielRamosAcosta, the examples on the `examples` directory should work out of the box. You can try the [insecure](https://github.com/SUSE/Portus/blob/master/examples/compose/docker-compose.insecure.yml) one in order to get an idea on how to deploy Portus.

Moreover, we have recently upgraded the documentation, so we are now providing a [How to Deploy](http://port.us.org/docs/deploy.html) page as well.
