### ISSUE TITLE
Explicit Roadmap >2.4

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1692]
Lets also create two new project entries 
**2.5** and **2.6** 
We are already starting to fill up 2.5 and >2.5  so we should make this explicit and transparent.

**Comment by mssola** [comment]
That's true. I've just added the 2.5 project, since we already had planned for the 2.5 milestone. As for the 2.6 release, we don't want to plan so far ahead, so we will come back to this whenever we release 2.4

Moreover, after releasing 2.3 we will also refine our current "To do" column for 2.4 and 2.5 since they are a bit messy right now :sweat_smile: 

Does this sound good ?
