### ISSUE TITLE
Add a new docker-compose example for version 2.3 including clair and webpack

### ISSUE THREAD

**Issue by suntorytimed** [SUSE/Portus#1714]
### Description

The current secure docker-compose example (master/examples/compose/) doesn't provide all new features of v2.3 (f. e. clair) and strongly differs from the development docker-compose.yml in master/

If clair and webpack are production ready those should be added to the example or an additional secure example should be created to support an easier setup of an up to date production environment.

**Comment by mssola** [comment]
> If clair and webpack are production ready those should be added to the example or an additional secure example should be created to support an easier setup of an up to date production environment.

As part of a re-implementation of the integration testing I'm currently working on (see #1667), I'll also provide an example with Clair in it. That being said, webpack is not needed. That's because production images will already have all the assets compiled, so we don't need a process to compile them :wink: 

I'll keep this open as a documentation issue as a reminder to provide the example. Thanks for the feedback :+1: !

**Comment by suntorytimed** [comment]
Thanks for the clarification concerning webpack and the addition to milestone 2.4.

**Comment by mssola** [comment]
@suntorytimed I've just tested it and the example provided by #1716 should just work. Thanks for the feedback! :+1:

**Comment by suntorytimed** [comment]
@mssola Thanks for the example. As far as I can see this is based on the insecure setup. I will enhance it to a version with SSL encryption using nginx, test it and submit a pull request.
