### ISSUE TITLE
How to curl a registry using portus? [question]

### ISSUE THREAD

**Issue by Vesli** [SUSE/Portus#1715]
Hello, waiting for the background to be operational (2.3 still having error and if I try :head it tells me that it's waiting for the DB to be available) I would like to use the /v2/_catalog endpoint of my private registry.

But I'm facing issues trying to access it from curl or postman.

The best I had so far doing this process:

> https://portus.domain.com:3000/v2/token?account=Admin&client_id=docker&offline_token=true&service=docker.domain.com:5000

Then I try to do my curl with the bearer token returned by portus.
But in the front I've got an "UNAUTHORIZED" and in the logs I've the `error authorizing context: insufficient scope`

I've tried the `--cacert`  option in order to pass the certificate as well, but same result :(

Am I missing something?

**Comment by mssola** [comment]
You could try with the rails runner `bin/client.rb`. It assumes that you have already configured a registry. So you can ping it like this:

```
$ docker exec -it <container-id> portusctl exec rails r bin/client.rb ping
```

This runner is mostly used for development purposes, that's why it's not documented... It has other commands like:

- catalog: it will fetch and print the registry catalog.
- manifest: if you give it a `imagename:tag`, it will download and print the image manifest.
- delete: if you provide the name, a digest and a final string (only possible values "blob" and "manifest"), it will delete the given digest from the registry.

Hope it helps!

**Comment by Vesli** [comment]
Ah yeah it does! Thanks a lot Miquel, I've to say that you've always been of a great help.

**Comment by wesm-outreach** [comment]
@mssola does the private registry endpoints just not work?

**Comment by mssola** [comment]
@wesm-outreach they do. We use this task instead so, among other things, the Portus config and the current registry as stored in the DB are taken into account when performing some actions.
