### ISSUE TITLE
Remove users/teams/namespaces/registries

### ISSUE THREAD

**Issue by DirkHeinke** [SUSE/Portus#177]
Is it planned to build routes for deleting users/teams/namespaces/registries?

To delete the registry would be interesting because currently only one is supported, and you can't change it.

**Comment by flavio** [comment]
Yes it is. Right now distribution (the registry v2) doesn't have delete capabilities. We are going to add the possibility to remove users, teams, images,... as soon as this is implemented inside of distribution.

**Comment by DirkHeinke** [comment]
Sorry if I'm wrong, but I thought the registry would only have to support the deletion of images. The authentication is handled completely by the index?

**Comment by flavio** [comment]
You are right, registry is only aware of images.

We will have to take care of user removal, but we cannot do that right now because we cannot propagate the removal event from portus to the registry. When removing an user portus will also remove all the images inside of his private namespace for example.
