### ISSUE TITLE
docs: add migration path from RPM to container

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1799]
### Description

Right now there is no clear path in regards to how to migrate from an RPM installation to a containerized scenario. We should add a page on http://port.us.org talking about this.

**Comment by jordimassaguerpla** [comment]
What about something like this?

In short, the portus image does not contain the database nor the registry, just portus, so you don't need to migrate anything, but just start the docker image with the env variables as stated in the deploy section (http://port.us.org/docs/deploy.html#docker), so that they point to the DB configuration.

**Comment by mssola** [comment]
> In short, the portus image does not contain the database nor the registry, just portus, so you don't need to migrate anything, but just start the docker image with the env variables as stated in the deploy section (http://port.us.org/docs/deploy.html#docker), so that they point to the DB configuration.

Yeah, it should be simple. The only thing to be done is to backup the database, point the MySQL container into the proper directory, and then just deploy Portus and all the components as containers. It should be pretty straight-forward, people just need to go a bit careful with the DB as always :wink:

**Comment by mssola** [comment]
Fixed by #1805.
