### ISSUE TITLE
[Question] What features use the SMTP configuration ?

### ISSUE THREAD

**Issue by Hugo1380** [SUSE/Portus#1982]
The question is : what happen and what is the features of Portus can not use without an SMTP configuration ?

Can I avoid to set an SMTP server ?

Thank you,

**Comment by mssola** [comment]
The idea is that in some places Portus needs to send an email. Right now, and if I recall correctly, this only happens when users forget their passwords. In this case, they can go to a form in which, upon entering their email, will send them a mail with some instructions. That being said, in the future there might be other features that might need to send emails.

> Can I avoid to set an SMTP server ?

Then Portus will assume that `sendmail` has been configured locally (the default command then is `/usr/sbin/sendmail -i -t`).

Hope things are more clear now :smile:

**Comment by Hugo1380** [comment]
Thank you, that's clear for me ! :)
