### ISSUE TITLE
Some Socket and SSL Errors

### ISSUE THREAD

**Issue by adilmobiliz** [SUSE/Portus#2086]
Hello,

I have followed this guide: https://github.com/SUSE/Portus/tree/master/examples/compose

I've created the keys and put them to the ```secrets``` folder. I put my custom to .env and nginx.conf.

.env:
```MACHINE_FQDN=my.domain```

nginx.conf:
``` 
    server {
    listen 443 ssl http2;
    server_name my.domain;
```
When I try to add a new registry, I get this error:

![screenshot_20190108_143704](https://user-images.githubusercontent.com/33028996/50828644-021a4480-1353-11e9-8958-c69033628a72.png)

There are also TLS errors in the Docker logs:

```registry_1    | 2019/01/08 11:39:05 http: TLS handshake error from xx.xx.xx.xx:53510: tls: first record does not look like a TLS handshake```

Is it possible to run Portus without SSL? I have looked at the documentation. However, I didn't see such as info.

How can I resolve this issue?

Thanks

**Comment by mssola** [comment]
> Is it possible to run Portus without SSL? I have looked at the documentation. However, I didn't see such as info.

It is indeed possible. Take a look at the [insecure example](https://github.com/SUSE/Portus/blob/master/examples/compose/docker-compose.insecure.yml). That being said, as explained [here](https://github.com/SUSE/Portus/tree/master/examples/compose#certificates) you should anyways create certificates, so that the registry can verify that Portus is the proper authentication service. So, after generating this self-signed certificate, with the insecure example you should be good to go.
