### ISSUE TITLE
Run registry 2.0 as part of our docker-compose setup

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#217]
As per subject.

**Comment by rtrauntvein** [comment]
I started looking at submitting a PR for this but realized there are a few things to think about before really adding in a registry.

Here are some of my thoughts on the docker development environment:

* Registry and Portus SSL certs
 * Documentation to generate Self Signed certs / Or to use own trusted CA signed certs
 * Document or automatically setup certs in Rails webserver SSL configuration
 * Document or automatically setup Portus to Registry SSL configuration options
 * Document differences for boot2docker (not a big priority)

* Registry configuration
 * Questions: How much registry configuration should Portus itself do?
 * Storage volume - Is ephemeral storage ok or do we provide a way to do persistent storage?
 * Do we want to include a redis container also for registry caching

**Comment by lsamayoa** [comment]
@rtrauntvein I was also doing that too, in here: https://github.com/Gobliip/Portus/tree/ISSUE-217
And I have the same questions as you. 

Since the docker-compose.yml is dev only for now, I was considering just having a registry with ephemeral storage, at least for a proof of concept. I was trying to configure everything trough [docker/distribution] ENV overrides to get something hackable for devs.

[docker/distribution]: https://github.com/docker/distribution

**Comment by flavio** [comment]
I think we can close the issue right now. Feel free to open a new one if you think it's worth to tackle also more complex deployments.
