### ISSUE TITLE
compose helm

### ISSUE THREAD

**Issue by CorentinDy** [SUSE/Portus#2175]
### Description

Hi, 
I'm wondering if i want to change de main os from the Dockerfile and wanted to use my custom image with Helm, should it work ?

The question is not related to the build of the docker image but: 
If I build my images with docker compose, changing the OS with Centos (for example), I push those images on a custom repository and use them with Helm, is it supposed to work or should I use another procedure to get this working ? 

I can clarify if needed, not sure if it's understandable.

Thanks

**Comment by mssola** [comment]
I believe it should work, since there is nothing openSUSE-specific in the end result (you'd have to modify zypper commands to dnf for CentOS, and stuff like that). To be honest I've never tried it myself, but with some changes on the way you build the image it should really work.

I'm going to close this issue, but feel free to ask further if you have more doubts on this topic.
