### ISSUE TITLE
Can't connect ui to registry while building docker from example ssl with clair

### ISSUE THREAD

**Issue by stevenmcastano** [SUSE/Portus#2196]
I'm trying to build from the example for clair with SSL and getting errors while trying to link the registry to ui.

It's giving me SSL errors no matter what I try with self signed certificates.

Basically just to try things out I ran a "docker-compose -f docker-compose.clair-ssl.yml up -d"

I'm able to log into the UI afterwards once I accept the self sign SSL cert, but when I enter the FQDN for the registry, even with adding an entry to /etc/hosts, it still will not connect.

This is on release version 2.4.3

**Comment by RjEcho217** [comment]
MAN!!! I spent no joke 2 weeks trying to figure out how to make the certs work within these in the docker-compose bridge network. I got a CA from our DC and used self signed cert and put htem EVERYWHERE that the base OS of each image uses and used update-ca-certificates in each of the places it looks via the Man page... Hoping for a resolution because long term use will be hard to use in docker.... 

I do wonder if "bare metal" works better.
