### ISSUE TITLE
Unexpected 401 error after getting Portus information

### ISSUE THREAD

**Issue by leandrorusso** [SUSE/Portus#2260]
### Description

While using Portus,  if you will execute into Portus frontend container the command below:
"docker exec -it <container-id> portusctl exec rake portus:info"

The current users logged will be redirected to the login page.
Portus container logs show:
Processing by TeamsController#index as HTML
Completed 401 Unauthorized in 6ms (ActiveRecord: 0.9ms)

**Portus version**:2.5.0

**Comment by Jean-Baptiste-Lasselle** [comment]
HI @leandrorusso , If there is **anything** (I mean, any, thing), you would like to do with rake inside portus container, you can also do it using Portus API and curl. Or `portusctl`, but I don't recommend `portusctl`, because : 
* `portusctl` is badly coded in golang
* `portusctl` is absolutely not maintained
* and `portusctl` does nothing that `curl` does not do a `10^32` (around the _Avogadro_ number) times better.
 * and we rar ein the cloud, we use REST API, SystemD or SystemV is a Jurassic debate :)

see https://github.com/SUSE/Portus/issues/2244#issuecomment-585557198
