### ISSUE TITLE
if I don't login, I can't pull image from private registry?

### ISSUE THREAD

**Issue by LeonLuHan** [SUSE/Portus#258]
I login by admin first, and then I push my image my.registry:5000/test:v1 to registry and suceed. Then I logout and try to pull my image from registry failed.

Pulling repository my.registry:5000/test:v1
Error: image test:v1 not found

What should I do?

**Comment by flavio** [comment]
What do you meant with logout? Are you talking about the web UI or the `docker` command line tool?

You always have to be logged into the registry (note well, registry not portus) with the command line client in order to either pull or push.

**Comment by LeonLuHan** [comment]
@flavio I log out from registry with `docker` command line client. I meant to pull image without logging in registry. Now, I know that I have to log in into the registry first. Thanks!!

**Comment by hanej** [comment]
@flavio I would actually like to be able to pull from the Docker registry without authorization but any pushes would require authorization.  The majority of images that are built are done through continuous integration which are locked down so we would leverage the tokens in Portus for that.  It's the pulling that is a problem right now since we don't want passwords or tokens hanging around on the file system.  Is this possible?

**Comment by mssola** [comment]
@hanej repos in public namespaces can be pulled without authentication. See PR #468 :) This is available in version 2.0 of Portus. Is this what you were asking ?

**Comment by hanej** [comment]
That should do it!  Thank you for the quick response, @mssola
