### ISSUE TITLE
Is it possible to restrict account creation?

### ISSUE THREAD

**Issue by deitch** [SUSE/Portus#283]
Is it possible to restrict account creation, so that not everyone can set up an account? As I understand it now, anyone who can access the Portus web UI can set up their own account and then push/pull images. Is it possible to prevent that?

**Comment by vitorarins** [comment]
I am running the Portus app inside a Local Network, so that is not a problem right now for me. But I am thinking of deploying Portus in our Cloud servers, and I will need to set up a VPN access only to the server in order to circumvent that problem.
It would be nice if there was an e-mail configuration, so that every user that tries to set up an account has to be approved by the admin or something like that.

**Comment by deitch** [comment]
I think a request-approval process is as good as an admin-creation process. Either works.

**Comment by mssola** [comment]
Hi @deitch and @vitorarins , this is some of a duplicate of the issue #179. As I said there, I'd like to bring LDAP support first before doing anything on this regard. Therefore, after LDAP support is implemented, I will take a look at this.

**Comment by vitorarins** [comment]
Hi @mssola , sorry I missed that issue before commenting on this one. In my particular case I wouldn't use LDAP here in the company, but surely is a great feature to have. Thank you for the great app BTW.

**Comment by mssola** [comment]
Fixed, see the issue #179.
