### ISSUE TITLE
First push - notification timeout

### ISSUE THREAD

**Issue by dohnto** [SUSE/Portus#394]
Hi! I just started with Portos and I try to get it work starting with docker-compose (compose-setup.sh). I can successfully push to docker registry, but no changes are visible to Portus web (no repo visible). 

With my naive approach I came to this: Portus receives a web notification from registry and then tries to retrieve a manifest (in order to determine tag of pushed repository). Then it finds out that it needs to acquire a token in order to see the manifest. Then Portus requests for token with user portus in method `Portus::HttpHelpers::get_response_token` which timeouts and that is why I see no changes in web/database. 

This is from my point of view caused because the web is running as a single instance and the `Net::HTTP::request` is synchronous (?) and therefore cannot verify the user and generate a token.

Is this expected to happen? Am I the only one who run into this situation? Am I doing something wrong? Is there any workaround (I tried to start the portus web with `thin start --servers 3 -p 3001` and running nginx which load-balances port 3000 to 3001-3003, but with no success).

Any help would be appreciated.

**Comment by mssola** [comment]
Hi @dohnto, as a matter of fact, today I wrote a wiki page specifically for this: https://github.com/SUSE/Portus/wiki/An-NGinx-setup. Hope it helps :P

From your explanation, make sure that your NGinx config really handles the Thin servers you're creating. Also, make sure that you've configured everything correctly, so double-check hostnames, ports, etc. Moreover, if you're using SSL you should tell Portus that your registry is using SSL (see [this PR](https://github.com/SUSE/Portus/pull/363)).

Otherwise, if your problem persists, you should give us your NGinx config, more details on your setup, etc.

**Comment by dohnto** [comment]
Ok I will look at that, as I can see this, this is a duplicate of #373. But as I can see this, the scenario is different than you describe there.

1) Push to Docker Registry (user -> registry)
2) Registry sends webhook to Portus web (registry -> portus)
3) Portus web asks for manifest (portus -> registry) (this succeed!)
4) Registry responds that a he needs an authentication token.
5) Therefore Portus web asks for permissions of user `portus` with passwod `portus1234` (portus -> portus !!!) but never receives an response because it is blocked and timeouts.

Am I right?

**Comment by dohnto** [comment]
Ok, I was able to resolve this issue. If anyone stucked as me, you can try to make the `thin` to run in multiple instances and then configure a nginx to load-balance between them. The idea is same as @mssola described in wiki. The problem was with configuration of registry where I missed line: `http://web:3000/v2/webhooks/events` and forgot to change the port number. You can close this issue.

**Comment by mssola** [comment]
I was about to look into the issue now :D Good to know that it works for you.
