### ISSUE TITLE
Improve how the admin creates the registry on Portus' database.

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#408]
When adding a registry user has to specify the name of the registry and its hostname. This is a bit misleading however, because to get everything working you also have to put the port # on which the registry is listening if the port number is different from 80/443. 

We should make the UI clear about what has to be provided inside of the hostname field.

**Comment by mssola** [comment]
The main problem is that if the user does not write the hostname:port properly, then it can get stuck with an invalid configuration. So, there is some work to be done to address this:

[ ] Allow the admin to rename the hostname if there are no repositories.
[ ] Be more explicit on the UI about what has to be provided in order to create the registry.
[ ] On creation, test whether the registry is reachable or not. If it is not, warn the admin that is not reachable. Then it's up to the admin to decide whether the hostname should be changed, or if he wants to go through anyways.
[ ] Allow `portusctl` to create the registry when setting Portus up for the first time. Maybe extend that so non-portusctl users can do this too.
