### ISSUE TITLE
Repositories always 0 in all namespaces

### ISSUE THREAD

**Issue by tuxknight** [SUSE/Portus#419]
I could't see any repositories in Portus   after  pushed several images to portus registry.

**Comment by gbisheimer** [comment]
Had the same issue. If you are using docker-compose, you can run
`docker exec portus_web_1 /bin/bash -c "CATALOG_CRON=10.seconds bundle exec crono"` to start the crono service with 10 seconds sync period, as stated [here](https://github.com/SUSE/Portus/wiki/Synchronizing-the-Registry-and-Portus).

I couldn't get docker registry notifications working yet, but still working on that.

**Comment by wangchunyang** [comment]
I have the same issue. I checked the logs and found the connection to registry was refused. Because I'm using 127.0.0.1:5000 as registry. I think we shouldn't use 127.0.0.1 in portus_web_1 container to connect portus_registry_1 container. We should try to use a IP or hostname which is accessible for portus_web_1 container.

**Comment by flavio** [comment]
> We should try to use a IP or hostname which is accessible for portus_web_1 container. 

Yes that's right. This is also specified at the end of docker-compose setup (see [here](https://github.com/SUSE/Portus/blob/master/compose-setup.sh#L93))

**Comment by flavio** [comment]
I will close this issue given we already have issue https://github.com/SUSE/Portus/issues/418 to track @gbisheimer's comment.
