### ISSUE TITLE
Could Portus Record The Image ID For Pushed Images?

### ISSUE THREAD

**Issue by GrantStreetGroup** [SUSE/Portus#512]
It would be great if Portus recorded and displayed the ID of the image for each tag.  

We generate images often and it would be nice to know with ID was in the registry compared to local.

Short ID like: 0064fda8c45d

**Comment by mssola** [comment]
Agreed.

**Comment by GrantStreetGroup** [comment]
Happy to help with this, if you have pointer of where in the code to look?

**Comment by mssola** [comment]
The implementation is a bit tricky to be honest, since this info has to be handled gracefully by both the [catalog job](https://github.com/SUSE/Portus/blob/master/app/jobs/catalog_job.rb) and the [events controller](https://github.com/SUSE/Portus/blob/master/app/controllers/api/v2/events_controller.rb).

**Comment by GrantStreetGroup** [comment]
I can see the 'digest' in the events payload..  not sure where it would be in the catalog request (if at all)?
