### ISSUE TITLE
Cloud deployment

### ISSUE THREAD

**Issue by boyand** [SUSE/Portus#538]
Hey guys, 

I have a private repository running on the cloud and I would like to use Portus as authentication provider and allow only authenticated parties to access the repository over the Internet. The biggest challenge with the current implementation is that it bundles together auth and UI administration and more importantly, it allows users to register on their own. This is really a big show stopper as I wouldn't want to expose a UI to the world where everyone can register. 

By looking at the current configuration, I guess I could configure a reverse proxy exposing /v2/ to the world and disabling the access of anything else unless it comes from a trusted origin. Would that work? Do you have other suggestions?

**Comment by mssola** [comment]
Hello @boyand !

> I have a private repository running on the cloud and I would like to use Portus as authentication provider and allow only authenticated parties to access the repository over the Internet. The biggest challenge with the current implementation is that it bundles together auth and UI administration and more importantly, it allows users to register on their own. This is really a big show stopper as I wouldn't want to expose a UI to the world where everyone can register. 

So, if I read it correctly you have two issues here:

1. Users should not be able to register: this is a known issue, and it's currently on the works. You might want to subscribe to the issue #179.
2. The authorization service is glued to the UI: this has honestly been done on purpose. Otherwise how would you manage the permissions of each users, create namespaces, etc. ? We believe that a nice web UI on top of all this is easier to manage and more comfortable. However, if you have an idea on this, please don't be shy ;)

> By looking at the current configuration, I guess I could configure a reverse proxy exposing /v2/ to the world and disabling the access of anything else unless it comes from a trusted origin. Would that work? Do you have other suggestions?

If you want to check configurations on the matter, you might want to take a look at [this NGinx configuration](https://github.com/SUSE/Portus/wiki/An-NGinx-setup), or most probably, [this configuration](https://github.com/SUSE/Portus/wiki/Portus-and-Docker-registry-on-the-same-FQDN-using-sub-URI) in which we setup Portus and the registry on the same FQDN. Now, what you propose also sounds good, and it might work, but the devil is in the detail ;) Maybe you might want to provide provide the configuration you're working on so we can help you out :)

**Comment by boyand** [comment]
Hi @mssola, 

Thanks a lot for your quick feedback. You are sport on - the main challenge is the users sign up form being enabled by default. Thanks for pointing out the issue - I am following it now. Once it is resolved, I think the setup I have in mind will work flawlessly. 

The configuration I am working on looks like this: 

<img width="239" alt="portus" src="https://cloud.githubusercontent.com/assets/4598763/11061542/1e0e7cb8-87a8-11e5-8a6a-5981ac6d9356.png">

**Comment by mssola** [comment]
@boyand After that issue is closed, this setup you're trying to implement should be supported.

**Comment by mssola** [comment]
@boyand note that in the code of current master this has already been implemented. There is one small extra feature that is left to be done, but besides that, now it should work just fine for you ;)

**Comment by mssola** [comment]
@boyand this is now implemented and documented. You can read about the feature itself [here](http://port.us.org/features/disabling_signup.html) and how to configure it [here](http://port.us.org/docs/Configuring-Portus.html#disabling-the-sign-up-form).
