### ISSUE TITLE
Handle global namespaces

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#57]
Right now we do not allow users to pull and push to the global namespace. We should change that.

Every time a new Registry entry is created we should immediately create a Namespace with name `nil` and public set to `true`. Only admin users should be allowed to push to this namespace. We should also show this namespace in a special way inside of the UI.

**Comment by flavio** [comment]
@mssola warning: I have some code already done. Wait a little before jumping on this issue

**Comment by mssola** [comment]
@flavio got it :)

Just a thought though: wouldn't it be better if instead of checking the name of the namespace, we introduce a new column `special`, or something like that? Without diving too much into the code, this way we wouldn't have to work-around the validator for the name of the namespace when creating this global namespace.

**Comment by flavio** [comment]
Good point, let me think about it.

**Comment by flavio** [comment]
Closing, fixed with [this](https://github.com/SUSE/Portus/pull/70) pull request.
