### ISSUE TITLE
Any hint around building an HA Portus based solution

### ISSUE THREAD

**Issue by rds13** [SUSE/Portus#572]
I'm willing to use Portus to handle my registries and to build an HA solution.
In my setup Portus use LDAP. LDAP is already setup with on two distinct servers.
I understand Portus DB can be setup in master-master but if my users register on one Portus instance do I have to make sure they stick on that instance ? Can I share session information across Portus instances ?
May be those questions are more on the rails side but I'm sure some pointers in the wiki would be helpful on that subjects.

**Comment by mssola** [comment]
Hi @rds13, you're right, we don't have any examples of multiple Portus instances running at the same time. Right now, the one that might be closer to your case might be the [NGinx](http://port.us.org/docs/setups/3_nginx_bare_metal.html) one. In my opinion it shouldn't be too hard to migrate this setup into an HA one.

> I understand Portus DB can be setup in master-master but if my users register on one Portus instance do I have to make sure they stick on that instance ? Can I share session information across Portus instances ?

Shouldn't your database configuration and your haproxy config already deal with this ? On the top of my head, you could just point both Portus instances to the same database, so there wouldn't be any problems with users using one instance or the other. And haproxy should already take care of which instance to use.

All in all, I honestly haven't looked into this topic, since we haven't had any scenario so far in which this kind of setup made sense. I don't have the time to provide one myself right now though :/ I'll leave this issue open, in the hopes that someone steps in with some configuration about this :)

**Comment by dpetzel** [comment]
I stumbled across this today while researching the issue for our own setups. Its not clear to me if Portus works with any other backends aside from MariaDB, and I'm not that familiar with it, but it seems that [Galera](http://galeracluster.com/) you can provide an active/active DB solution for MariaDB. It seems that the rest of Portus should just scale out behind a load balancer. I guess it depends on where the session information is stored if you'd need to use sticky persistence or not.

In our case we are looking to span multiple data centers with some potentially high latency so I'm not sure an active/active MariaDB solution will cut it for use case (still getting up to speed on what exactly is in the DB and what the impact of replication latency might be)

**Comment by duffqiu** [comment]
any update for ha solution right now? thanks

**Comment by mssola** [comment]
See the [How to deploy](http://port.us.org/docs/deploy.html) page. In there you will find instructions on how to install Portus with Helm and Kubernetes. I'd recommend using this setup for an HA deployment of Portus. If you have any more questions on this topic, refer to [this repo](https://github.com/kubic-project/caasp-services/tree/master/contrib/helm-charts/portus), where they will provide you with more info. Thanks!
