### ISSUE TITLE
No Release v2 package

### ISSUE THREAD

**Issue by owenhaynes** [SUSE/Portus#598]
Looks like there is no package for V2 of portus,  even the daily snapshots packages seem to be outdated no build since October, wanting to upgrade from V1.

**Comment by mssola** [comment]
We're on it ;)

**Comment by protomouse** [comment]
Subscribing to this. Also, a package for Leap 42.1 would be much appreciated.

**Comment by jordimassaguerpla** [comment]
We are actually enjoying our hackweek right now. I'll review it next week. There is some rubygem dependencies that we have to fix. Sorry for that.

**Comment by owenhaynes** [comment]
See the Portus 2 package now, to update is it a simple case of an update or are there any extra commands todo?

**Comment by jordimassaguerpla** [comment]
Hi! Sorry when we develop the v2 RPM we didn't define an update path from a previous v1 RPM. We plan to provide that from now on.

I'll figure out a workaround and I'll get back to you with an answer.

**Comment by flavio** [comment]
Database migrations are going to be automatically executed on the 1st run: https://github.com/SUSE/Portus/blob/master/config/environments/production.rb#L85

Apart from that I think there's nothing else pending... isn't it?

**Comment by jordimassaguerpla** [comment]
The problem is that we changed the way configuration variables are set. In version 1 portus was relying on apache variables while in version 2 is a mix of yml files that we set running "portusctl setup".

**Comment by flavio** [comment]
You should take a backup of your machine and of your database.

Then:
  * update to latest portus package
  * restart the apache process
  * log into portus

On the 1st load of the page the rails process is going to take a while to start, that's because the database migrations are performed in the background.

If something goes wrong with the apache configuration you should follow the instructions we have on our website and use the `portusctl` tool to recreate apache's configuration.

I hope that helps.

The upgrade paths from v1 to v2 has not been tested because v1 has never been supported by SUSE. However v2 is fully supported, so all the upgrade paths from now on are going to be officially supported by us.

**Comment by JonathonReinhart** [comment]
Sorry for being a noob, but how do we update to v2?

```
# zypper update Portus
Retrieving repository 'openSUSE-13.2-Update' metadata ...........................................................................[done]
Building repository 'openSUSE-13.2-Update' cache ................................................................................[done]
Loading repository data...
Reading installed packages...
No update candidate for 'Portus-20151027090209-1.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...

Nothing to do.


# cat /etc/zypp/repos.d/Virtualization\:containers\:Portus.repo 
[Virtualization:containers:Portus]
name=Virtualization:containers:Portus
enabled=1
autorefresh=1
baseurl=http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/openSUSE_13.2/
path=/
type=rpm-md
keeppackages=0
```

**Comment by flavio** [comment]
This is the repository that builds the package from master.

The repo for the v2 branch is:

http://download.opensuse.org/repositories/Virtualization:/containers:/Portus:/Release:/2.0.0/openSUSE_13.2/

**Comment by JonathonReinhart** [comment]
@flavio Sorry, but when you say "*This* is the repository...", what does "This" mean?

I'm assuming you mean that http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/openSUSE_13.2/ is built from the `master` branch. However, it was never updated.  Is it intended that it will be updated?

For a "stable" install, it sounds like following the repository that tracks the v2 branch is the best idea. Is this correct?

Could someone confirm that my use of `zypper install --oldpackage Portus-2.0.0` (after adding the v2 repo) was correct? It seems like a quirk, because of the naming scheme (2015 vs 2.0.0), but I'm not sure.

Thanks!

**Comment by flavio** [comment]
> I'm assuming you mean that http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/openSUSE_13.2/ is built from the master branch. However, it was never updated. Is it intended that it will be updated?

It should be automatically updated on a daily basis. If not it's a bug. @jordimassaguerpla could you look into that please?

> For a "stable" install, it sounds like following the repository that tracks the v2 branch is the best idea. Is this correct?

Yes. It's correct.

> Could someone confirm that my use of zypper install --oldpackage Portus-2.0.0 (after adding the v2 repo) was correct? It seems like a quirk, because of the naming scheme (2015 vs 2.0.0), but I'm not sure.

Yes, that's correct.

Sorry for the long delay, holiday + ongoing sickness

**Comment by JonathonReinhart** [comment]
Thanks for confirming all of that.

> Sorry for the long delay, holidays + ongoing sickness

Not a problem! The same has been happening on this side of the pond :-)

**Comment by jordimassaguerpla** [comment]
Hi! We were missing a new gem dependency in that repo and thus Portus was not building. Sorry about that.

All dependencies are building now and Portus just started to be rebuild. Expect a new package soon in http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/openSUSE_13.2/

**Comment by jordimassaguerpla** [comment]
You have a package build from latest commit from master now.

For openSUSE 13.2:

http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/openSUSE_13.2/

For Leap:

http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/openSUSE_Leap_42.1/
