### ISSUE TITLE
Add Registry Management Features...

### ISSUE THREAD

**Issue by ArcticSnowman** [SUSE/Portus#642]
In an ideal world the feature of Portus and https://github.com/kwk/docker-registry-frontend would be combined into a single front end to provide authentication, access control and registry management.

**Comment by mssola** [comment]
This is the first time that I've seen this project, so excuse me if I haven't understood it correctly. For what I understand, this is a full-fledged web UI for the docker registry (with authentication through Kerberos possibly ?). To be honest, I don't see how both projects can be configured to interact with each other, since I see too many conflicts. For example, access control is implemented in Portus' side. This information is not available outside of Portus, meaning that you couldn't manage that using `docker-registry-frontend`'s UI.

In order to implement that, we should:

- Separate better between UI and Authentication.
- Implement most of Portus' controllers as a "stable" API, usable outside of Portus.

All this is *way* out of our scope. I'm not saying that we will never do this, we just have too many things in our plate right now that we want to care of. We can re-visit this on the future, but I'm closing this for now.

**Comment by ArcticSnowman** [comment]
@mssola -  I was only thinking that the registry management features seen in the docker-registry-frontend could find there way into the Portus roadmap.   Like you said neither application will play nicely with the other.  And I just want to bring this item to your attention.

Thanks for the great work on Portus BTW.

**Comment by mssola** [comment]
Oh, I see. We already have lots of ideas for the next milestone and we'll certainly check for the features that are available in `docker-registry-frontend`. Thanks :)
