### ISSUE TITLE
Define registry using Env Vars on docker startup

### ISSUE THREAD

**Issue by sshipway** [SUSE/Portus#655]
It would be very useful to be able to define the linked Registry automatically when the Portus container starts up, by passing the credentials in environment variables.  

In this way, I'd be able to have a docker compose that creates the mariadb container and the portus container, automatically creates the database, and defines the registry to link to, so that the wohle system will come up in one go.

**Comment by egidijus** [comment]
In production we exported the database with docker registry configured, and imported to AWS RDS.
Since our portus and registry are stateless (all images are saved to AWS S3), we can just replace the containers that run nginx/portus/regsitry.

While testing on my local machine, I was working with tutum's mariadb image - which can be told to import sql dump on startup.

You could write an additional startup bash script for compose that does not remove the database container.

**Comment by mssola** [comment]
This should be pretty easy to achieve (e.g. adding some simple code in the `db/seeds.rb` file), and it's embarrassingly old...

**Comment by lightlace** [comment]
>  by passing the credentials in environment variables.

Sounds a little unsafe to me.. do you really want to store your password in an environment variable?

**Comment by mssola** [comment]
> Sounds a little unsafe to me.. do you really want to store your password in an environment variable?

What I'm talking is about allowing people to register the Registry with env variables: the name, hostname and use_ssl. That's it. So it shouldn't be unsafe.
