### ISSUE TITLE
push and pull to/from team namespace

### ISSUE THREAD

**Issue by fahimeh2010** [SUSE/Portus#657]
hello all
First thank you for your open source project.
Actually I do not know how user push to team name space? I read all this (http://port.us.org/features/3_teams_namespaces_and_users.html) but still have no clue. I am using your appliance (http://port.us.org/docs/setups/2_appliance.html) 
Thank you very much

**Comment by fahimeh2010** [comment]
I have this log 
E, [2016-01-11T11:15:17.292089 #1404] ERROR -- : Mysql2::Error: Field 'repository_id' doesn't have a default value: INSERT INTO `tags` (`user_id`, `created_at`, `updated_at`) VALUES (1, '2016-01-11 11:15:17', '2016-01-11 11:15:17')

**Comment by mssola** [comment]
Hi,

You should [create a team](http://port.us.org/features/3_teams_namespaces_and_users.html#teams). Then, in this team you can create all the namespaces you want, and assign team members. Let's say that the namespace you are trying to push into is named `example`, and your registry has the hostname `registry.test:5000`. In this case, you should login with the proper user and perform:

    $ docker push registry.test:5000/example/image

Isn't this working for you? It would be useful if you could tell us which version of the appliance you have.

**Comment by fahimeh2010** [comment]
yes I created a team and add namespace named "example" to team and then try to push it in the way you mentioned but failed( users can login successfully). in the log it say there is no namespace with that name "example". and when i looked at namespaces table, "example" exists but registry_id is NULL.
what can I do?
thanks a lot

**Comment by mssola** [comment]
And are you sure that said user has access to that namespace ? (either the namespace is public or the user has owner/contributor permissions in the team).

> and when i looked at namespaces table, "example" exists but registry_id is NULL.

This is really weird. Which version of the appliance are you using ? Are you re-using the database from a previous version ?

**Comment by fahimeh2010** [comment]
yes the user has contributor permission in the team.
i use 1.0.1 image appliance, i downloaded it on (http://port.us.org/docs/setups/2_appliance.html) .
Are you re-using the database from a previous version ? No , I use the database on the appliance i downloaded

**Comment by mssola** [comment]
This looks weird. Anyways, bear in mind that 1.0.1 is a pretty old version. Moreover, the appliance was just a technical preview (not documented, sorry). You have multiple ways to get a proper version:

- [docker-compose](https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment) or [Vagrant](https://github.com/SUSE/Portus/wiki/Vagrant-environment). Ideal if you are just messing with Portus and you want to take a look how everything works.
- The [RPM package](http://port.us.org/docs/setups/1_rpm_packages.html), which will give you a more permanent and easy solution if you are an openSUSE user (even though you'll have to restart from scratch, since you have already installed the appliance).

After that, try again and tell me if everything is fine now. Sorry for the inconvenience.

**Comment by fahimeh2010** [comment]
I can install portus by compose-setup.sh on every linux distribution? 
Thanks a lot

**Comment by fahimeh2010** [comment]
it worked and there is no that problem, thank you so much, issue is closed
