### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by h0tbird** [SUSE/Portus#670]
The currently produced docker image is huge.
Feel free to use [h0tbird/docker-portus](https://github.com/h0tbird/docker-portus) as a guidance (about 200MB).

**Comment by egidijus** [comment]
+1
thanks h0tbird

**Comment by mssola** [comment]
Wow, good to know :) ! We'll update it as soon as we can

**Comment by egidijus** [comment]
@h0tbird I strongly recommend you use pongo-blender instead of marathon.
single binary jinja2 template generator https://github.com/madedotcom/pongo-blender
here is an example APKBUILD file for your alpine: https://github.com/madedotcom/alpine-packages/blob/master/main/pongo-blender/APKBUILD

pongo blender will use env vars injecter to container.

example:
* Create a `vars` file
```
vim vars
```
with something like this
```
export SHOES="green"
export CATS="cute"
export STATE="busy"
```

* Create a `template` file with something like this
 ```
my shoes are {{ SHOES }}
my cats are {{ CATS }}
my state is {{ STATE }}
```


* Run pongo-blender passing it values for variables you want set
```
. vars && pongo-blender template > output
```

* The output file is a complete with your variables and template stuff
```
egidijus@ub-sol:/tmp/pongos$ cat output 
my shoes are green
my cats are cute
my state is busy
```

**Comment by h0tbird** [comment]
@egidijus `marathon` is a container scheduler that runs as a framework on top of a `mesos` cluster.
I see `pongo-blender` as a complementary tool to generate marathon definitions by interpolating envars. Thanks for the recommendation.

**Comment by egidijus** [comment]
@h0tbird we made pongo-blender because our devs needed to test things locally without having mesos, it's a cheap and easy way of injecting configs at runtime.

**Comment by flavio** [comment]
@h0tbird thanks for the tips. There's however an issue with the registry configuration: you are not configuring a notification endpoint. This will prevent real-time updates inside of Portus.

Unfortunately last time I checked (before Christmas 2015) it wasn't possible to configure a notification endpoint via environment variables. The env variables allow you to specify key/value settings where values can be only strings. Unfortunately the notification endpoints are a list of maps.

**Comment by h0tbird** [comment]
@flavio Thank you I just forgot to push that part. The [new](https://github.com/h0tbird/docker-registry/releases) `h0tbird/registry:v2.2.1-3` (or `:latest`) can be used to setup one endpoint.

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
