### ISSUE TITLE
Use of Application Token

### ISSUE THREAD

**Issue by jgsqware** [SUSE/Portus#679]
Hello

I would like to know how to use the Application Token.

I supposed it's for request a token for the registry?

Do I use it when requesting http://172.17.0.1:3000/v2/token?service=172.17.0.1:5000&scope=repository:jgsqware/ubuntu-get:pull

Thanks in advance

**Comment by mssola** [comment]
I'm not sure what do you mean by "Application Token" :) Do you mean the JWT token being used by Portus to communicate with the registry? (that users shouldn't touch directly)

**Comment by jgsqware** [comment]
No the Application Token from here: http://localhost:3000/users/edit

![application token](https://cloud.githubusercontent.com/assets/3304363/12558245/e90455f6-c38e-11e5-8c99-d096d32c2478.png)

**Comment by mssola** [comment]
Oh right! I thought that this was merged into the `hackweek` branch :) But yes, now I remember that we decided to put it in master. So, this token should be used in Docker CLI to authenticate yourself. For example:

    $ docker login my.registry:5000 -u mssola -p <token> -e email@example.com

We are doing this because this password will be saved in your home without encryption by the docker daemon. Thus, you can avoid putting your real password there by just using these random tokens (especially useful for LDAP users).

**Comment by jgsqware** [comment]
OK thanks

I'm trying to get a Auth token from Portus to speak with the registry and I
was thinking that's like application token from Facebook to authenticate an
app and not a user.

**Comment by mssola** [comment]
@jgsqware for now it's just for the user to cover this case. Maybe in the future we can do something more with it. Let's see :)
