### ISSUE TITLE
Introduce the idea of "Display name", to avoid confusion in LDAP

### ISSUE THREAD

**Issue by linbaiye** [SUSE/Portus#699]
Hi, there:
Thanks for this great project first. After setting up  portus, I noticed that the 'ldap name' used to login does not match with the 'user name'. For example, if I use the ldap name 'bob.bob' to login, the dashboard will show it as 'bobbob', the dot is missing. Have you deliberately decided to make it show in this way?

**Comment by mssola** [comment]
Hello. Yes, that's correct behavior. The thing here is that even if LDAP servers allow characters such as dots and so on, Docker doesn't. Because of that, Portus adheres to what Docker allows in the username of users. See [this](https://github.com/SUSE/Portus/blob/6059cfd78950e002c6e2c3d559dfb7fea3d6a129/lib/portus/ldap.rb#L163).

That being said, in Portus we still store the original name in the DB so if you do something like this it will work:

    $ docker login -u bob.bob

We don't show `bob.bob` in the UI because that would be confusing. Every user has assigned to it a personal namespace, and something like `bob.bob` is not a valid namespace in docker (that's why we transform it into `bobbob`). Maybe we could show the original LDAP name in the UI ? I have mainly two objections with that:

1. For namespaces/repos, this would be outright lying, because the real namespace is `bobbob`, since it's what docker expects. If we used the LDAP name, then users might be tempted to tag repos with a namespace `bob.bob`  which is wrong, thus adding confusion upon users.
2. For places where we are only strictly speaking about the user itself (e.g. the users container in the admin panel, the name on the top right corner to access the profile, etc.) this might be ok. That being said, I'm not entirely convinced on the idea, since it might also be confusing for someone that
 says "ok, if my user is `bob.bob`, then I most surely have my `bob.bob` personal namespace". This is again misleading. Moreover, in the user container of the admin panel, then we would be showing names that are not matching any of the existing namespaces, which is equally misleading.

Note that we already describe this situation in our [LDAP documentation page](http://port.us.org/features/2_LDAP-support.html#ldap-user-authentication). Besides that, I'm not sure what we can do from our side in order to improve this situation. I'm open for ideas, but for now I find any alternative solution to be either misleading, or outright lying to users.

**Comment by mssola** [comment]
@lonewulf said on #700:

> Hi,

> If I may, I would be in favor of adding a display name to the users, the namespaces still would be the username (with Docker restrictions) but it would be a far more user friendly experience for the feeds and team management (especially when usernames have absolutely nothing to do with people names).

> It would also be great if LDAP is in use to be able to pull this field from an LDAP (same principle that guess_email)

> The personal repository is already in its own tab, so I would think it not misleading for the user to have a display name and a username.

> Regards,

**Comment by mssola** [comment]
> If I may, I would be in favor of adding a display name to the users, the namespaces still would be the username (with Docker restrictions) but it would be a far more user friendly experience for the feeds and team management (especially when usernames have absolutely nothing to do with people names).

Again, I don't know how I feel about this, but I don't have any strong opinions :) @flavio @jordimassaguerpla @cyphar what do you think ?

> It would also be great if LDAP is in use to be able to pull this field from an LDAP (same principle that guess_email)

With the `guess_email` attribute we define a policy which is based on simple things. I don't know how that would apply for usernames. Do you have any idea ? Maybe we can have this attribute to configure this exact discussion ? (about whether to show modified names or not).

> The personal repository is already in its own tab, so I would think it not misleading for the user to have a display name and a username.

Fair enough.

**Comment by lonewulf** [comment]
@mssola : There is a pretty simple solution, if the display name is empty, then display the username, though I wouldn't allow users to change that attribute by themselves if ldap is in use as ldap should be the reference for such information.

**Comment by linbaiye** [comment]
@mssola , thanks for your reply. I'm ok with the username, as long as it's not a bug.

**Comment by flavio** [comment]
I think we could introduce a the concept of "display name", pull it from LDAP whenever possible and show prefer it to username in some places of the UI. Basically what @lonewulf proposed above.

However I don't see that as a urgent feature.

**Comment by mssola** [comment]
Ok, I see. Let's do that then.

**Comment by mssola** [comment]
@linbaiye I also took the liberty of modifying the original title to reflect better what we agreed on what's the actual issue. I hope you don't mind.

**Comment by mssola** [comment]
Closing in favor of #736.

**Comment by mssola** [comment]
This issue and #736 are slightly different. Re-opening :sweat_smile:
