### ISSUE TITLE
rubygem-passenger-apache2 undocumented dependency

### ISSUE THREAD

**Issue by opichon** [SUSE/Portus#708]
I'm trying to install portus-2.0.1 but it says "nothing provides rubygem-passenger-apache2 needed by Portus-2.0.1-2.1.x86_64". This is not documented in the package's dependencies. Please advise.

**Comment by mssola** [comment]
From which repo have you download it ?

/ping @jordimassaguerpla

**Comment by opichon** [comment]
http://download.opensuse.org/repositories/Virtualization:/containers:/Portus:/Release:/2.0.1/openSUSE_Leap_42.1/x86_64/Portus-2.0.1-2.1.x86_64.rpm
I am running this image on AWS EC2: openSUSE-Leap-42-1-v20151123-hvm-ssd-x86_64 (ami-5e1bda3d)

**Comment by mssola** [comment]
I can reproduce this, we're on it.

**Comment by jordimassaguerpla** [comment]
Passenger is also in the same location:

http://download.opensuse.org/repositories/Virtualization:/containers:/Portus:/Release:/2.0.1/openSUSE_Leap_42.1/x86_64/

You better add it as a repo:

zypper ar http://download.opensuse.org/repositories/Virtualization:/containers:/Portus:/Release:/2.0.1/openSUSE_Leap_42.1/

zypper install Portus

That should fix it.

Otherwise, please reopen this bug.

**Comment by opichon** [comment]
thanks
