### ISSUE TITLE
Portus local registry

### ISSUE THREAD

**Issue by opichon** [SUSE/Portus#711]
I've run portusctl setup --local-registry, but portus UI still asks me to configure a registry. 
portusctl setup has modified the /etc/registry/config.yml file to include what seems the appropriate settings to authenticate via portus. So why is portus still asking me to configure a registry?

**Comment by mssola** [comment]
This is explained in [this](http://port.us.org/docs/Configuring-the-registry.html) documentation page. But, I'd agree that every "Setups" page (e.g. the "RPM packages" page) should include a link to this page right in the end.

Long story short, we also need to add the configuration of the registry to Portus' DB so the special `portus` user can interact with your registry. We know that this can be a bit cumbersome for RPM users, since the `portusctl` tool could already do that (see #421). We plan to fix this soon.

I'll keep this issue open as a reminder that we need to improve the documentation in this regard.

**Comment by flavio** [comment]
@mssola we should also change portusctl to print some warning when --local-registry is passed and the registry package is not found.

**Comment by mssola** [comment]
@flavio agreed. I just opened #712.

**Comment by opichon** [comment]
I suggest it might be less confusing if portusctl setup did NOT make any change to the local registry, and if the user was left to configure his local registry directly. This would at least make it clear that the installation of the registry is separate from the installation of portus. 

Of course, that would require some good documentation. 

An alternative could be to have a separate portusctl command.

As I mentioned in another ticket, the fact that portusctl setup makes changes to the existing configuration can  be quite annoying at times. Using a separate command would isolate the registry config from any changes when portusctl setup is run repeatedly.

**Comment by mssola** [comment]
> I suggest it might be less confusing if portusctl setup did NOT make any change to the local registry, and if the user was left to configure his local registry directly. This would at least make it clear that the installation of the registry is separate from the installation of portus. 

As specified in #712, I think that we should ask the user whether or not to replace an existing `config.yml` file.

> An alternative could be to have a separate portusctl command.

That also looks like a good suggestion.

**Comment by flavio** [comment]
> I suggest it might be less confusing if portusctl setup did NOT make any change to the local registry, and if the user was left to configure his local registry directly. This would at least make it clear that the installation of the registry is separate from the installation of portus. 

The configuration of the registry is not really easy, and despite all our efforts there are still going to be users not reading the docs.

The purpose of `portusctl` is to get you started from scratch, that's why it creates/overwrites the configuration files. We never intended `portusctl setup` to be used as a way to upgrade Portus' configuration. I made some suggestions on issue #712 to prevent this type of unwanted situations.
