### ISSUE TITLE
remote registry configuration

### ISSUE THREAD

**Issue by opichon** [SUSE/Portus#713]
The documentation in the "How-to-setup-secure-registry.html" page, "Configuring the Registry in a safe way" section is confusing.

In the 'auth/ token" section, you keep using "my.registry" as a placeholder for both the registry and the portus server. This is bound to cause total confusion, especially as the original docker registry docs is not that much clearer. 

As far as I can understand (and this is also the only way I could make it work):
realm: refers to the portus url, e.g. https://portus.mydomain.com/v2/token
issuer: portus hostname, e.g. portus.mydomain.com
rootcertbundle: certificate of portus server, e.g. /etc/nginx/ssl/portus.mydomain.com.crt

but service refers to the registry, e.g. my.registry:5000

Also the notifications/url should be the portus server's url.

There is a typo in the text "issues" instead of "issuer".

**Comment by mssola** [comment]
Agreed, we should fix typos and bad writing. Thanks for reporting.

**Comment by tinybitsofnothingness** [comment]
@Portus developers: I really appreciate your enormous effort with developing this package, but there is a general confusion regarding setting up this project for production. It would be really great to consolidate all the questions/answers and update documentation with proper and complete steps to run Portus in production, maybe even including steps which are not directly necessary for Portus but should be done on host itself (e.g. copying certificates to proper folder on host and similar).

**Comment by mssola** [comment]
Hi @tinybitsofnothingness. Yes, we are aware of all the different setups in which Portus can be run, and we are aware that we didn't write good documentation in regards to how to setup Portus in production (besides the RPM setup). Since we are a small team, we decided to initially start by providing a good experience with the RPM, and leave other setups for development purposes from our part. This has allowed us to focus on Portus itself, while providing a good base on how to run Portus on other setups. That being said, we are now currently on the works to provide a better experience with Portus in a containerized environment, and we will document it every step of the way.

**Comment by tinybitsofnothingness** [comment]
@mssola Sounds great! To be honest, I would help you with it, but I still didn't completely clear the confusion out in my own head :) If you think there is a way I could do, let me know, I'll give my best to help!

**Comment by mssola** [comment]
The PR #1056 is about fixing the original issue. The problems pointed out by @tinybitsofnothingness have been already submitted in other issues with the `documentation` tag (plus, once that set of issues are fixed, I'll give the documentation some more cleanups and such).
