### ISSUE TITLE
Can't sync Portus with registry

### ISSUE THREAD

**Issue by HipsterWhale** [SUSE/Portus#718]
I'm currently evaluating Portus, and I'm confronted to a major issue. The part for the authentication works well, I can log and I can push images. But, I can't view the content of my registry.

The registry seems to send correctly the event, but something goes wrong. Did I miss something, or is this a bug ?

Here is the puma output :

```
Started POST "/v2/webhooks/events" for 172.18.0.11 at 2016-02-09 19:32:38 +0000
Processing by Api::V2::EventsController#create as JSON
Could not fetch the tag for target {"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>711, "digest"=>"sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd", "length"=>711, "repository"=>"test/busybox", "url"=>"http://repo.ponyland.fr/v2/test/busybox/manifests/sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd"}
Reason: execution expired
```

**Comment by mssola** [comment]
This is something that we fixed quite recently. See commit 575d51b3b7d2c60fe22d6ec526f761616604ccd4. What version of Portus are you using?

**Comment by HipsterWhale** [comment]
Good to know, I'm currently on this version : `master@8e7eb21` I cloned the git repository this morning.

**Comment by mssola** [comment]
Now I see what's going on. According to the `mediaType`, the manifest being pulled to get the info of the tag being pushed is [v2.2](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md). This is alright, but apparently the code to handle this in our side assumes that there's a `tag` attribute in that manifest (because it was on v2.1), but this is not the case in this new format. I'll take a look on how to fix this. Thanks for reporting!

**Comment by HipsterWhale** [comment]
No problem :). Let me know when a fix will be available on master.

Great work by the way

**Comment by HipsterWhale** [comment]
I found a way to fix the issue, I'm going to do a pull request soon.

**Comment by JonathonReinhart** [comment]
Since Docker doesn't seem to be the most stable software in the world, perhaps a "compatibility matrix" might be useful to have, in the README or Wiki?

**Comment by HipsterWhale** [comment]
@JonathonReinhart :+1:

**Comment by mssola** [comment]
@JonathonReinhart I agree.

**Comment by mssola** [comment]
@HipsterWhale I've added a fix on the PR #725. Could you give it a try ? :P 
@JonathonReinhart in the PR #725 I've added a table specifying the "compatibility matrix". My plan is to also add it in our `gh-pages` branch.

**Comment by JonathonReinhart** [comment]
@mssola Looks great. Thanks @mssola.

**Comment by wolfch** [comment]
Hi, I updated to the latest commit, 197d2bddcd7ab8fa77876f9a97d3df5706d2f238 and, for me, Portus is still not syncing with the registry.  Here is what I see in the registry 2.2 debug log:

```
9.28.167.17 - - [10/Feb/2016:20:13:16 +0000] "PUT /v2/testns/busybox/manifests/cwolf1 HTTP/1.1" 201 0 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.16.0-60-generic os/linux arch/amd64"
2016/02/10 20:13:16 http: TLS handshake error from 172.17.42.1:46555: tls: first record does not look like a TLS handshake
```
where 172.17.42.1 is the docker0 interface for 9.28.167.17


...and in the corresponding Portus web log:
```
web_1   | [16] 172.17.42.1 - - [10/Feb/2016:20:13:16 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.0735
web_1   |
web_1   |
web_1   | Started POST "/v2/webhooks/events" for 172.17.42.1 at 2016-02-10 20:13:16 +0000
web_1   | Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1   | Processing by Api::V2::EventsController#create as JSON
web_1   |   Registry Load (0.1ms)  SELECT  registries.* FROM registries WHERE registries.hostname = 'csx00273.canlab.ibm.com:5000' LIMIT 1
web_1   |   Namespace Load (0.1ms)  SELECT  namespaces.* FROM namespaces WHERE namespaces.registry_id = 1 AND namespaces.name = 'testns' LIMIT 1
web_1   | Could not fetch the tag for target {"mediaType"=>"application/vnd.docker.distribution.manifest.v1+json", "size"=>2742, "digest"=>"sha256:a77fab8e17310b77266ff2874b3ba31c44400db95bf91dc0b0daf87b8f98e7aa", "length"=>2742, "repository"=>"testns/busybox", "url"=>"https://csx00273.canlab.ibm.com:5000/v2/testns/bus
ybox/manifests/sha256:a77fab8e17310b77266ff2874b3ba31c44400db95bf91dc0b0daf87b8f98e7aa"}
web_1   | Reason: wrong status line: "\x15\x03\x01\x00\x02\x02"
web_1   | Completed 202 Accepted in 86ms (ActiveRecord: 2.8ms)
web_1   | [12] 172.17.42.1 - - [10/Feb/2016:20:13:16 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.1330
```
It seems like one of the Portus components is trying to access an https endpoint with plain http, or the inverse.  I'm thinking this is maybe because I have the registry running with SSL but Portus web is still trying plain http.  

Here is the relevant portion of my registry config:
```
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
  tls:
    certificate: /var/lib/certs/registry.crt
    key: /var/lib/certs/registry.key
  secret: b71c7815b82a49e91e602ce0bbc54085
auth:
  token:
    realm: http://csx00273.canlab.ibm.com:3000/v2/token
    service: csx00273.canlab.ibm.com:5000
    issuer: csx00273.canlab.ibm.com:5000
#    rootcertbundle: /var/lib/certs/registry.crt
    rootcertbundle: /var/lib/certs/portus.crt
#    rootcertbundle: /etc/docker/registry/portus.crt
notifications:
  endpoints:
    - name: portus
      url: http://csx00273.canlab.ibm.com:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

**Comment by mssola** [comment]
@HipsterWhale note that the patch has not been merged into master :) (use my branch to try it out :P). Regarding SSL, have you told Portus that your registry is using SSL ? See [this](http://port.us.org/docs/Configuring-the-registry.html).

**Comment by wolfch** [comment]
@mssola, that was me, @wolfch commenting about the hybrid Registry with SSL/Portus with plain http.  I forgot about the SSL switch for the registry in the GUI because I initially got errors when I switched it on, but now, when I switch it on - no errors, so I will wait for cronos to do the next sync to see of the TLS error goes away.

Meanwhile, since I _am_ using Registry-2.2 - how do I pull/clone your branch to get the v2 manifest fix?

**Comment by wolfch** [comment]
Now am am getting:
`registry: 2016/02/10 21:10:42 http: TLS handshake error from 172.17.42.1:46575: remote error: unknown certificate authority`

`crono_1 | Exception: SSL_connect returned=1 errno=0 state=unknown state: certificate verify failed`
because the cert was signed by a self-signed root CA - how can I configure Portus to know about the full chain, or to ignore SSL verification?

I am thinking about hacking 'lib/portus/http_helpers.rb' in the function 'perform_request' and somehow set: 

```
Net::HTTP.verify_mode = OpenSSL::SSL::VERIFY_NONE
```
So I can use self-signed issuer and/or certificate, unfortunately I have nearly zero experience with Ruby.  

I don't if `verify_mode ` is a class-level or instance-level property - I would guess instance-level, in which case I would need to refactor the code to have access to the `Net::HTTP.` instance _before_ calling `const_get`. I will google the Ruby API/laguage docs...

**Comment by mssola** [comment]
> Meanwhile, since I am using Registry-2.2 - how do I pull/clone your branch to get the v2 manifest fix?

This issue is about [Manifest 2, Schema 2](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md). This is only supported by registry 2.3 and docker 1.10. So you first would have to upgrade both :) After that, well, just pull from my clone. If you are in `master` and you are not afraid to experiment, one way to do is is to add my repo as a remote, fetch it and check out the branch.

**Comment by wolfch** [comment]
I will stay with registry 2.2 and docker 1.9 for now, in that case.  But now I still have the issue self-signed CA and/or server cert.  Instead of changing code, I will see about getting the CA into the container's `/etc/ssl/certs`...

**Comment by wolfch** [comment]
I went into the running cronos container and `scp` the self-signed CA certs and updated the `/etc/ssl/certs` via this procedure:
https://www.brightbox.com/blog/2014/03/04/add-cacert-ubuntu-debian/
...and now Portus successfully connects!  

Unfortunately, it still doesn't display the  repo/tags in the GUI.  The catalog request worked:
`172.17.42.1 - - [10/Feb/2016:23:19:03 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 2
00 52 "" "Ruby"`

...however when it tried to get a tag list for a repo in a namespace not known by Portus, it got:
`172.17.42.1 - - [10/Feb/2016:23:19:03 +0000] "GET /v2/cwolf/busybox/tags/list HTTP/1.1" 401 145 "" "Ruby"`
with addtional error of:
`level=warning msg="error authorizing context: insufficient scope"`

The issue seems to be that the image was pushed via the docker CLI, which will just create whatever namespace you give as a prefix for the repo, regardless of what's in the Portus database.  I would have expected Portus to create any new namespaces from the result of the CatalogJob - is that not how it works?

**Comment by wolfch** [comment]
Ok, I created the missing namespace via the GUI and now the cronos job successfully populated the repositories and tags in the database and displays them in the GUI.  So the issues are:

1. Automated way to populate custom CA certs into the container(s) upon startup
2. Namespaces that exist in the registry but in in Portus `namespaces` table should not prevent  syncing. In fact, I would expect for new namespaces found by the CatalogJob to create new entries in the `namespaces` table rather then depend an admin user to have to do it in the GUI
3. As per item number 1, above - not sure if webhooks would work - I think that another container...

**Comment by HipsterWhale** [comment]
Working well for me, thank you very much !
