### ISSUE TITLE
Crono fails on first unsuccessful attempt

### ISSUE THREAD

**Issue by dohnto** [SUSE/Portus#720]
I am trying to use Portus with docker-compose from master (8e7eb218b1d9d7b9d5534b9784ba199d201fab72) but I am using my external registry with already images in it.

Suppose I have already two images in my registry:

* `ns/repo1`
* `repo2`

and I have not created the `ns`  namespace in Portus. The crono job will try to sync the registry with portus db.

1. Crono successfully catalogs the registry
2. Crono tries to get token for `ns/repo1` but fails (because Portus does not know `ns` namespace)
3. (not happened) Crono tries to gets for `repo2` and and inserts entry to Portus db.

The third step did not happen, because the step 2 failed even-though it may pass. 

Is this scenario even supported?
Shouldn't the Crono iterate over all entries even when previous failed or some inconsistency can be met?

Thanks for answers.

**Comment by mssola** [comment]
> 
1. Crono successfully catalogs the registry
2. Crono tries to get token for ns/repo1 but fails (because Portus does not know ns namespace)
3. (not happened) Crono tries to gets for repo2 and and inserts entry to Portus db.

Step 2 is working right now. We cannot create a namespace on-the-fly, because it has to be assigned to a team, and to some admins, which in turn have some permissions on it. We have to investigate on how to automate this process, but for now this is not supported.

Step 3 is a bug :D The PR #721 should fix that. Thanks for reporting :)

**Comment by mssola** [comment]
@dohnto fixed! I've also cherry-picked the fix into the `v2.0` branch.
