### ISSUE TITLE
Github / Jenkins integration / support

### ISSUE THREAD

**Issue by egidijus** [SUSE/Portus#759]
**Context:**
We have experimented with various approaches of tagging images.

If we tag an image with the jenkins build number, we have to go to jenkins to check commit hash, to then check github to then check the commits/changes added to the image.

If we use commit hashes to tag images, we can look in github to check changes, but hashes are less people friendly when looking in jenkins and portus.

So we tag with both, because tags cost nothing.

**Feature:**
Jenkins has a "changelog" plugin that pulls github commit changes for each build. This way you can - at-a-glance see what is new in a build - this is super useful.
https://wiki.jenkins-ci.org/display/JENKINS/Git+Changelog+Plugin

But when an image ends up in portus, it is not clear/easy to tell how image tag 01 is different from 02 and why, unless you have access to gihub, or jenkins or both.

Something like this would increase portus' value.

**Comment by holgerreif** [comment]
It tokk me a while to get a clue what your feature request might be about... I try to state it with my words:
_Provide a plugin for portus in order to retrieve specific information about an image (here: changelog from github) based on the tag of an image (here: github commit hash) and display it._

I doubt, that adding a plugin infrastructure might be on roadmap.

What we had done with kwk/docker-registry-frontend is to hack a button into the repository listing page that contains an URL pointing to our internal wiki. The repository part of the wiki-URL gets replaced with the actual repository that is displayed.

Back to portus. One simple solution is to use a template for the documentation page and define a few placeholders like %TAG%, %REPONAME%, %IMAGENAME% etc. that gets replaced with the actual values. You can contruct an URL that points to the specific github commit based on the tag (which actually happens to be the commit hash). This way you can access the information with a simple click.

@egidijus Does this proposal help you with your problem?

**Comment by egidijus** [comment]
That sounds like it would get us a long way to the goal.
Thank you!!
