### ISSUE TITLE
2.3 Authentication Failure with pre docker 1.10 clients

### ISSUE THREAD

**Issue by owenhaynes** [SUSE/Portus#766]
Hi,

The authentication seem to be failing for docker clients 1.7 - 1.9 when using registry 2.3, i see the conversion of the manifests take place in the docker register logs and then see a authentication failure. 

May not be a Portus problem, need to do a little more investigation when i get time.

docker 1.10 clients work fine

Portus 2.0.2

**Comment by owenhaynes** [comment]
Only seems to happen with images pushed from a 1.10 client and downloaded byt a 1.9 client or below.

**Comment by cyphar** [comment]
@jordimassaguerpla *gulp* Looks like this answers our migration questions. :/

**Comment by jordimassaguerpla** [comment]
Hi! Thanks for reporting it. Docker 1.10 introduced a new "manifest format" which requires images to be migrated. Looks like once docker performes the migration, images are not usable anymore with previous versions of docker.

Could you clarify what you mean by "authentication failure"? Because I see you state that it does not happen if you push images with 1.9.

Is the failure on "docker pull"? or is it on "docker login"?

**Comment by owenhaynes** [comment]
docker pull, You see in the logs that it knows the images are incompatible and converts the 1.10 image to a 1.9 image and then you just get a message about authentication error, and docker pull fails

Need to re set up registry 2.3 as i had to downgrade to bypass this issue, so will get some message later on

**Comment by mssola** [comment]
We have documented the supported versions. Please, take a look at [this page](http://port.us.org/docs/versions.html) for more info.
