### ISSUE TITLE
Why are usernames more restricted than namespace names?

### ISSUE THREAD

**Issue by eolamey** [SUSE/Portus#777]
Hi,

First of all, thank you all for your work. We have successfully deployed Portus with our private docker registry and it's working really well.

I was wondering if there's a reason, technical or otherwise, to restrict usernames to only lowercase alphanumeric characters, and therefore forbid dashes (for exemple). It seems a bit too restrictive, especially since a namespace is created per user, but namespaces don't have the same naming limitations (as far as I can see they are only limited in length).
Wouldn't it make more sense to restrict both namespace names and usernames the same way the docker registry does? I think they use this [regexp](https://github.com/docker/distribution/blob/master/reference/regexp.go#L18) but I'm not sure.

I can see the naming rules for usernames in the [documentation](http://port.us.org/features/3_teams_namespaces_and_users.html) but it's not entirely clear why it is so.

Sorry if this has been discussed before.

**Comment by mssola** [comment]
> I was wondering if there's a reason, technical or otherwise, to restrict usernames to only lowercase alphanumeric characters, and therefore forbid dashes (for exemple)

Agreed, it's a bit too restrictive. We do that for historical reasons I think, since we were trying to play safe to what the registry allows for namespaces. That being said, we do restrict namespace's names. See https://github.com/SUSE/Portus/blob/master/app/validators/namespace_validator.rb. The regexp we are using is actually *really* close to what's being accepted by the registry (I think that they have changed the format a bit across different releases...).

So,  you are raising two valid points:

- We could be less restrictive for user names (possibly the same as namespaces, but I should investigate whether there's anything that we didn't consider :P).
- We should take a look at the regexp for namespaces (e.g. see if it's the same for different registry's releases and so on).

**Comment by mssola** [comment]
This has already been fixed. You can now create use whatever user name you want.
