### ISSUE TITLE
cannot delete the comments

### ISSUE THREAD

**Issue by raghu999** [SUSE/Portus#805]
Hi i am Testing Portus Version: 2.1.0-dev i am unable to delete the comments . I am an Admin User . i am running with rack and rails env set to staging with compose setup.

<img width="1295" alt="screen shot 2016-04-08 at 10 24 06 am" src="https://cloud.githubusercontent.com/assets/12721392/14386753/12f7c5ae-fd74-11e5-8d4a-6c7fb2b8a5ca.png">

**Comment by flavio** [comment]
Can you look into the rails logs and see if there's some exception being logged?

**Comment by raghu999** [comment]
I see no Logs being Logged when i am clicking Delete

**Comment by flavio** [comment]
Which logs are you talking about: the one produced by the container or the Rails' logs?

We recently fixed the compose setup to ensure all the rails logs were sent to the stdout (and hence picked up by `docker logs`). Maybe you created your image before the fix was pushed to master...

The rails logs are under `logs/development.log`. You can try to get them via `docker exec`
