### ISSUE TITLE
when i want to upgrade or migra or backup portus's data,how to do that.

### ISSUE THREAD

**Issue by ghoul008** [SUSE/Portus#841]
BTW,when the master is available

**Comment by mssola** [comment]
> Upgrade Portus

If you are on openSUSE, then it's a matter of `zypper up`. Otherwise, you'll have to `git pull` on the current stable branch (`v2.0`).

> Migrate

It usually involves performing `rake db:migrate`. If you are using the RPM, then this will be done automatically when restarting apache. If there were any other migration steps, we would document it clearly (on the release notes and on http://port.us.org).

> Backup

This is not an issue within Portus itself :) Just use whatever tool you like to perform DB backups.

> BTW,when the master is available

What do you mean ?

**Comment by ghoul008** [comment]
i mean the master build failing,i can not use it for deploy.

**Comment by mssola** [comment]
@ghoul008 it is passing.

**Comment by ghoul008** [comment]
thanks
