### ISSUE TITLE
Production instructions for other operating systems?

### ISSUE THREAD

**Issue by petebowden** [SUSE/Portus#856]
I see the installation suggests using the SUSE RPMs for standing Portus up for production use. Unfortunately I cannot use a SUSE variant and must stick with CentOS/RHEL.

Does anyone have scripts or suggestions about how to run Portus in a production environment on CentOS/RHEL?

I'm no Ruby expert, so if this is information a Ruby expert would know how to do, please close and I can do more homework.

If not, any info people might have, I'd love to see shared and then added to documentation.

**Comment by mssola** [comment]
You've got multiple options:

- Try out the RPM anyways (I wouldn't recommend this, just in case there is some incompatiblity :wink:)
- I'm using [this](http://port.us.org/docs/setups/3_nginx_bare_metal.html) setup in development mode, but it can perfectly be run in production (it has NGinx with ssl and so on).
- You can go for a containerized setup. We are already working on a proper production-ready solution in this regard. Meanwhile, maybe you want to take a look at this [alpine-based image](https://github.com/h0tbird/docker-portus) that comes from the community. Otherwise, in the issues there have been multiple people that have shown how they deploy Portus in containers.

**Comment by Djelibeybi** [comment]
I wrote up my process and provide a sample repo: https://github.com/Djelibeybi/Portus-On-OracleLinux7 which should work on RHEL/CentOS.

**Comment by sgykfjsm** [comment]
Do you have a plan to release official latest Portus image? Actually, I need the latest.

**Comment by mssola** [comment]
We are now providing lots of production examples in the `examples` directory. But if you want to get more info check the [How to deploy](http://port.us.org/docs/deploy.html) page.
