### ISSUE TITLE
Upgrade portus

### ISSUE THREAD

**Issue by fahimeh2010** [SUSE/Portus#886]
Hello All

I am using portus but in this version I can not delete images, I want to upgrade it to the one that image deletion is possible(https://github.com/SUSE/Portus/issues/197), how can I do it?

Thank you very much

**Comment by mssola** [comment]
Hello. Unfortunately there's no upgrade method, but we have plans to fix this before releasing `v2.1.0`. For now, you will have to update your code to current `master` manually, but I don't honestly recommend that since you'd have to deal with some migrations and the possibility of it not being stable enough. I'd recommend to wait until `v2.1.0` is out (in August-September, we are also planning to release more often in the future :wink:).

I'm also going to close this issue, but feel free to write comments for any doubts. Also, bear in mind that we have a [Google group](https://groups.google.com/forum/#!forum/portus-dev), and these kinds of questions are more appropriate there :wink:
