### ISSUE TITLE
using portus in docker command line 

### ISSUE THREAD

**Issue by sagarbpatil007** [SUSE/Portus#933]
I have installed docker and my company has portus. like: dockerhub.co.xyz.com and repo : dockerrepo.co.xyz.com
How to push/pull into my repo in portus using docker command line. When I Use docker command line for pull/run I get proxy error.

New to docker. Completing docker tutorials. pardon me if this looks irritating.
Thanks

**Comment by mssola** [comment]
Hello @sagarbpatil007. Let's say that the Docker registry of your company is: `https://my.awesome.registry:5000`. Moreover, let's say that you have a user in  Portus named `mssola`, and that you want to push the image `alpine:latest` (and you already have it on your machine). For this, you first need to login (with `docker login my.awesome.registry:5000`). Once you do that, you will be able to push/pull. In this example, you *cannot* just do it like this:

    $ docker push alpine:latest

This is because `docker push` assumes the Docker Hub by default. In order to push to your company's registry, you'll have to inform docker about the location of it. You can do that by renaming this tag by prefixing the registry's hostname. In Docker, you use `docker tag` for that:

    $ docker tag alpine:latest my.awesome.registry:5000/mssola/alpine:latest

Notice two things:

1. The hostname does not include the "https://" part.
2. We are also including our username `mssola` in there. With this, you are informing Docker that your image will reside in the `mssola` namespace, which is your personal one (Portus creates a personal namespace for each user). Read more about how does Portus handle namespaces [here](http://port.us.org/features/3_teams_namespaces_and_users.html#namespaces).

After that, you can simply push there:

    $ docker push my.awesome.registry:5000/mssola/alpine:latest

> New to docker. Completing docker tutorials. pardon me if this looks irritating.

Don't worry. In fact, you made me realize that we don't have proper documentation for newcomers to docker :wink: (see #934).

**Comment by sagarbpatil007** [comment]
Thanks @mssola 
Actual problem was: How to get Docker to run on a Windows System behind a corporate firewall? ie. changing docker proxy.

Solved it. Reference: http://mflo.io/2015/08/13/docker-machine-behind-proxy/
