### ISSUE TITLE
With LDAP auth against AD, users seem to have higher piviledges that expected

### ISSUE THREAD

**Issue by AndreasKrause** [SUSE/Portus#966]
Hi,

given a Portus system based on the opensuse/portus image from Docker Hub (contains portus-2.1.0~dev+git050d095b08875306923663c8a1f9dfd9798bd0fb-5.1.x86_64). Portus authenticates against AD.

This works pretty well. Users are created on first login, together with their personal namespaces.

But there seems to be some problem with the permissions of each user being created: Users are able to create teams and namespaces regardless of their expected permissions. They even are able to delete tags and images in namespaces they shouldn't have write access to.

**Comment by mssola** [comment]
> Users are able to create teams and namespaces regardless of their expected permissions.

Well, any user can create teams and namespaces (note: not namespaces in any team, but they can create namespaces in their teams, yes). Are you expecting any option in which only admins would be able to create teams ?

**Comment by mssola** [comment]
> They even are able to delete tags and images in namespaces they shouldn't have write access to.

Fixed with #962 :yum:. Unfortunately, the Docker image does not get updated with every push. This is something that we need to fix. For now, you'll have to wait until it's rebuilt... Sorry about that :sweat:

**Comment by holgerreif** [comment]
> >  Users are able to create teams and namespaces regardless of their expected permissions.

> Well, any user can create teams 

Never tested it with non-admin accounts before, but according to [your comment](https://github.com/SUSE/Portus/issues/771#issuecomment-203915495)... 

 > So, what it's being proposed I think is that teams would still be created by Portus admins

...team creation should be an admin only right!

**Comment by mssola** [comment]
Argh, good point. It seems that we have some conflicting ideas here. Right now non-admin accounts can perfectly create teams and then create namespaces inside of it. I think that this is perfectly fine (e.g. think about how anyone can create teams in Github/Gitlab), but I would be ok about restricting this even further through configuration options. This would make sense in organizations where they want to keep a tight control of who owns what.

In that specific comment we were dealing about the idea of allowing multiple teams in a namespace. In that proposal we were re-shuffling quite a lot how teams/namespaces are managed in comparison to the current situation :sweat_smile:

Let's see, and maybe I'm contradicting with what I said in that issue (sorry about that). If I'm a non-admin of Portus that happens to be the owner of a team that owns a namespace, I should be able to add another team. Therefore, we should not require admin access for this (unless we add the configurable value I mentioned before). Also note that Portus administrators are, in practice, owners of all namespace, so that wouldn't cut down the privileges of admin accounts either. So, to sum it up, I think that what it makes more sense is to allow both owners of the owner team and administrators to add teams into a namespace (with a specific visibility).

What do you think ?

**Comment by holgerreif** [comment]
As I said, I never tested this before as regular user. 

And for simplicity I'd like to look at this issue completely decoupled from #771.

From an organizations perspective teams and moreover (from the registry's perspective) namespaces do have a global scope. An organization possibly wouldn't want a simple user to create a team and within the team a namespace e.g. _stable_. 

As a compromise the following would work in our scenario: A team is created by portus admin and the team owner (a dedicated responsible person) is given the right to create namespaces.

A more complete rights scheme would be:

1. Creation of teams:
   - admin privilege required 
   - no privilege required (default)
2. Creation of namespaces
   - admin privilege required
   - team owner privilege required 
   - team membership required (default)

Thus the defaults reflect the current situation, additional options would make it more suitable for organization's use. And it would fit with the discussions in #771, if we want the admin to create teams.

**Comment by mssola** [comment]
@holgerreif agreed in everything except for the second point. Right now, administrators and the team owners are the only ones that can create namespaces. And honestly, I'd like to keep it this way because otherwise what's the point of having team owners ? :wink:

Therefore, the only restriction the be made is who can create teams. Right now, anyone can do it, but we could provide a configurable value in which only administrators could do it.

**Comment by holgerreif** [comment]
@mssola you are right, again not enough tested... 

What about:

1. Creation of teams:
   - admin privilege required
   - no privilege required (default)
2. Creation of namespaces
   - admin privilege required
   - team owner privilege required (default)

Even if currently looks like a binary option I wouldn't implement it as binary flag, since this might cause problems in future whent the rights management scheme needs extensions...

**Comment by mssola** [comment]
Agreed :+1:

**Comment by mssola** [comment]
I'm closing this issue because the original question has already been covered.

@AndreasKrause if you have any more questions on this, feel free to drop comments here anyway or post on [our mailing list](https://groups.google.com/forum/#!forum/portus-dev).

@holgerreif if you want to continue this conversation, let's do it on #771. Anyways, I think that we have agreed on this :wink:
