### ISSUE TITLE
Admins should be marked as owners of teams

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#977]
Regular users might create a team, and then be tempted to add administrators of Portus as viewers. But this will be confusing because administrators can always push and administrate any team (thus, effectively being owners of all teams).

There might be multiple solutions to this issue, but I think that the best solution would be:

- Users are still allowed to add admins as viewers or contributors.
- Upon addition, they will get a flashy warning telling the current user that since it was an admin, it was promoted to owner of the team. This is better than disallowing the action altogether because we cannot forbid this from the UI (or at least not in a trivial/maintainable way).

**Comment by monstermunchkin** [comment]
I'm not sure about this. There's no point in adding an admin to any of viewers, contributors or owners since that won't change anything and therefore be useless.

We could just show a warning saying, it is not possible to assign an admin a role within a team. I cannot see why forbidding this would be non-trivial.

**Comment by mssola** [comment]
Because admins can be owners of a team. Let's say that I'm and admin and I create a new team. In this case I will be the owner of that team. This is completely redundant to being an admin in this case, but, because of the internal implementation, someone has to own a team.

That''s why I mentioned the idea of "promoting", because it plays well with the case I'm mentioning.

**Comment by monstermunchkin** [comment]
> Because admins can be owners of a team. Let's say that I'm and admin and I create a new team. In this case I will be the owner of that team.

You're right, I totally missed that point. Sorry :wink:

**Comment by holgerreif** [comment]
Beeing an admin is an additional role, maybe even a temporary one. What happens if the admin provs are dropped later?

Thus adding adding a person currently beeing an admin to a team is IMHO usefull. I would even keep the selected role, but show another icon (may a red man instead of a black one, of put thm a hat on), adjust the tooltip (e.g. to "owner and admin") and or place an exclamation mark with a tooltip after the name.

BTW nobody complains if you add user _root_ to _somegroup_ and _root_ is able to write an otherwise group-readable file...

**Comment by mssola** [comment]
> Beeing an admin is an additional role, maybe even a temporary one. What happens if the admin provs are dropped later?

> Thus adding adding a person currently beeing an admin to a team is IMHO usefull. I would even keep the selected role, but show another icon (may a red man instead of a black one, of put thm a hat on), adjust the tooltip (e.g. to "owner and admin") and or place an exclamation mark with a tooltip after the name.

That's true. That's why I'm saying that instead of not allowing it, we should "promote" the admin as an owner in that team, and tell the user about this. The bug is not on the underlying behavior, rather how we visually tell the user the capabilities of team members (e.g. telling that an admin user is a viewer, practically speaking, is lying, so we should tell the user that the team member will act as an owner).

> BTW nobody complains if you add user root to somegroup and root is able to write an otherwise group-readable file... 

Touché :wink:
